### ISSUE TITLE
リモートファイルの閲覧について

### ISSUE THREAD

**Issue by masatakayama** [ffftp/ffftp#103]
これまで1.98gを使っていましたが、この度64bit版の3.9にアップグレードしました。
リモートファイルの閲覧について、相違があり不具合が出ています。

1.98gではビューア1とビューア2（差分エディタ・WinMerge）を利用したとき、
ビューアに渡されるパスは以下のようになります。

ビューア1　通常のエディタ
c:\Users\us00010\AppData\Local\Temp\ffftp00003a00\file.htaccess

ビューア2　差分エディタ(WinMerge)
左側　C:\Users\us00010\AppData\Local\Temp\ffftp00003a00\file\remote..htaccess

しかし、3.9では、違うパス（正しくないパス）が渡され、閲覧ができません。

ローカルの初期ディレクトリ　Y:\a\html3

ビューア1　通常のエディタ
エディタで「\file.htaccess」が開けませんというエラーになる。
Y:\fileというディレクトリができていて、その中に.htaccessは存在する

ビューア2　差分エディタ(WinMerge)
右側のファイルのパスが
C:\file\remote..htaccess
となっている。
実際には、
Y:\file\remote..htaccess
に存在する。

初期ディレクトリが別の場合には、その初期ディレクトリにfileができてしまいます。
1.98gのようにテンポラリーなディレクトリに戻していただけないでしょうか？

**Comment by masatakayama** [comment]
これまで1.98gを使っていましたが、この度64bit版の3.9にアップグレードしました。
リモートファイルの閲覧について、相違があり不具合が出ています。

1.98gではビューア1とビューア2（差分エディタ・WinMerge）を利用したとき、
ビューアに渡されるパスは以下のようになります。

ビューア1　通常のエディタ
c:\Users\us00010\AppData\Local\Temp\ffftp00003a00\file\.htaccess

ビューア2　差分エディタ(WinMerge)
左側　C:\Users\us00010\AppData\Local\Temp\ffftp00003a00\file\remote..htaccess

しかし、3.9では、違うパス（正しくないパス）が渡され、閲覧ができません。

ローカルの初期ディレクトリ　Y:\a\html3

ビューア1　通常のエディタ
エディタで「\file\.htaccess」が開けませんというエラーになる。
Y:\fileというディレクトリができていて、その中に.htaccessは存在する


ビューア2　差分エディタ(WinMerge)
右側のファイルのパスが
C:\file\remote..htaccess
となっている。
実際には、
Y:\file\remote..htaccess
に存在する。

初期ディレクトリが別の場合には、その初期ディレクトリにfileができてしまいます。
1.98gのようにテンポラリーなディレクトリに戻していただけないでしょうか？

**Comment by sayurin** [comment]
修正します。 #102 で解決しているかもしれないので、確認します。

**Comment by sayurin** [comment]
確認の結果、#102 で修正した問題でした。報告ありがとうございました。次バージョンではテンポラリディレクトリを使用するように直ります。
