### ISSUE TITLE
デフォルトのローカルフォルダが原因で起動不可になる

### ISSUE THREAD

**Issue by Rukoto** [ffftp/ffftp#114]
はじめまして。
早速ですが不具合の報告です。

オプション＞環境設定＞転送2タブ　にある設定項目において、
「デフォルトのローカルフォルダ」は不正な値を許容します。
次回以降、起動時に不正なパスを参照してしまい強制終了します。
もちろん、レジストリによる設定の復元でも当該設定値が不正だと同じ状況が発生します。

設定を誤る場合もあるでしょうし、他から設定を引っ越す場合もリスクが発生します。
一般的なユーザーには今後一切起動できないという致命的な状況の発生が予想されます。

少なくとも起動時には当該値のチェックが必要なのでは、と愚行いたします。

なお、ツールやサウンド、ホスト設定毎のローカルの初期フォルダも不正な値を許容しますが、
起動に失敗するような致命的なものではない＆それぞれの挙動も異なるため、
これらは本issueとは無関係として取り扱いません。

ご確認の程、よろしくお願い致します。

**Comment by sayurin** [comment]
報告ありがとうございます。エラー処理するように修正します。
