### ISSUE TITLE
SOCKS 5 (ユーザ名、パスワード認証) で接続できません

### ISSUE THREAD

**Issue by mtzky** [ffftp/ffftp#141]
FireWall に SOCKS 5 (ユーザ名、パスワード認証) を設定し接続しようとすると、以下のエラーで接続できませんでした。
```
SOCKSサーバーの認証方式が異なります.
SOCKSサーバーに接続できません. (Err=-1)
```

Socks5Authenticate 関数で認証方式が以下の2つになっていますが、
https://github.com/ffftp/ffftp/blob/ce37be06db921f34eb6e2cc761f961af524a8754/connect.cpp#L1883

- X'00' NO AUTHENTICATION REQUIRED
- X'01' GSSAPI

ヘルプには `※SOCKS5のGSS-API認証はサポートしていません。` とありますし
[RFC1928 (SOCKS Protocol Version 5)](https://www.ietf.org/rfc/rfc1928.txt) を見る限り

- X'02' USERNAME/PASSWORD

の誤りでないかと思います。

ご確認いただけますでしょうか。よろしくお願いいたします。

**Comment by mtzky** [comment]
どちらかというと、SOCKS 5 プロキシサーバー側の検証していたときに
FFFTP をクライアントとして使わせていただきました。
以下 Dockerfile で検証環境作れるかと思いますので参考になると幸いです。

```Dockerfile
FROM alpine:latest

RUN set -x \
 && echo "@testing http://nl.alpinelinux.org/alpine/edge/testing/" >> /etc/apk/repositories \
 && apk --update add --no-cache dante-server@testing \
 && adduser -s /sbin/nologin -D -H proxyuser \
 && echo 'proxyuser:xpass' | chpasswd \
 && set - && { \
       echo 'logoutput: stderr'; \
       echo ''; \
       echo 'internal: eth0 port = 1080'; \
       echo 'external: eth0'; \
       echo ''; \
       echo 'socksmethod: username'; \
       echo 'clientmethod: none'; \
       echo 'compatibility: sameport'; \
       echo ''; \
       echo 'client pass {'; \
       echo '  from: 0.0.0.0/0 to: 0.0.0.0/0'; \
       echo '}'; \
       echo ''; \
       echo 'socks pass {'; \
       echo '  from: 0.0.0.0/0 to: 0.0.0.0/0'; \
       echo '}'; \
    } | tee /etc/sockd.conf

EXPOSE 1080

ENTRYPOINT ["/usr/sbin/sockd"]
CMD ["-f", "/etc/sockd.conf"]
```

**Comment by sayurin** [comment]
原因の特定およびDockerfileの提供までありがとうございます。修正したものを4.3としてリリースしますので、お待ち下さい。

**Comment by mtzky** [comment]
ご確認ありがとうございます。

お手数お掛けします。
よろしくお願いいたします。
