### ISSUE TITLE
アップロードに失敗する

### ISSUE THREAD

**Issue by tamura1195** [ffftp/ffftp#158]
ローカルの漢字コード Shift-JIS
ホストの漢字コード EUC
の設定でファイルをアップロードしようとすると、０バイトのファイルが生成されてアプリが異常終了します。

過去バージョンを試したところ、3.6では問題ありませんが3.7以降で発生します。

ご確認の程、よろしくお願い致します。

[イベントビューアー]
障害が発生しているアプリケーション名: ffftp.exe、バージョン: 4.3.0.0、タイム スタンプ: 0x5d9b3d1c
障害が発生しているモジュール名: ffftp.exe、バージョン: 4.3.0.0、タイム スタンプ: 0x5d9b3d1c
例外コード: 0xc0000409
障害オフセット: 0x00000000000eb589

**Comment by sayurin** [comment]
報告ありがとうございます。こちらでも再現できたので、修正できる見込みです。

**Comment by sayurin** [comment]
正規表現エンジンが貧弱なために発生していました。正規表現エンジンを変更したため改善される見込みです。

**Comment by tamura1195** [comment]
先程、v4.4をダウンロードして試してみました。
問題なく動作しております。
対応ありがとうございました。
