### ISSUE TITLE
バージョンの違いによる接続の失敗

### ISSUE THREAD

**Issue by jun1poko** [ffftp/ffftp#159]
同じFTPサーバに接続してのことです。

FFFTP4.3(x64)にて、暗号化なしでは接続できます。
FTPSのExplicit / Implicitどちらか・両方にチェックを入れると接続できなくなります。
FFFTP2.0(x64)では、暗号化なし、FTPSにチェックを入れても接続できます。

接続できないという書き方は正しくありません。正確には、

接続しました．
>MLSD
150 Opening data channel for directory listing of "/"
ファイル一覧の取得を中止しました．
ファイル一覧の取得に失敗しました・

となります。
試しに、FileZilla 3.45.1(x64)で接続してみたところ、接続できました。

どこか設定するべきところ、見直すべきところ、必要な情報はありますか？

**Comment by sayurin** [comment]
#153 で調査しましたが、2019/10のWindows Updateでセキュリティが強化されており、安全でないftpサーバーとは接続できなくなっています。ただし、接続拒否を行っているのはサーバー側ですのでサーバー個別に対応が必要となっています。
[Compatibility](https://github.com/ffftp/ffftp/wiki/Compatibility)にまとめている最中ですので、サーバー情報を教えていただけますでしょうか。

**Comment by jun1poko** [comment]
サーバ状態：
Windows 10 Pro (x64)、Build1903
FileZilla Server 0.9.60beta
OpenSSL 1.1.1d
ほかになにかありますか？

追伸：Cyberduckでも接続できました。

**Comment by jun1poko** [comment]
失礼、Build1903ではなくVersion1903です。

**Comment by sayurin** [comment]
FileZilla Serverはご自身でビルドされたものでしょうか？ [Download FileZilla Server for Windows](https://filezilla-project.org/download.php?type=server)で現在取得できるFileZilla_Server-0_9_60_2.exeですとOpenSSL 1.0.2kが使用されているようですが。

**Comment by jun1poko** [comment]
FileZilla_Server-0_9_60_2.exeをインストールしてます。
GUIで表示されるバージョン番号が0.9.60betaとなっておりました。
ビルドされているOpenSSL1.1.1dをインストール・証明書作成・署名して、
それをFileZilla Serverに登録しています。
そうかぁ、FileZilla Serverに内蔵のOpenSSLが使われるのですね。
これをキャンセルすることができないかを調べなければなりませんね。

**Comment by sayurin** [comment]
OpenSSLのインストール先に`libeay32.dll`と`ssleay32.dll`があればそれをFileZilla Serverのディレクトリにコピーすることで更新できるかもしれません。こちらでも確認してみます。

**Comment by jun1poko** [comment]
同名のDLLは存在しませんでした。
ビルドするしかなさそうですが、現在ビルド環境を作れないため、
後日試してみることになります。

**Comment by jun1poko** [comment]
FileZilla Serverの設定UIに

FTP over TLSをしている場合、PROT Pによるファイル転送を暗号化を強制する
PROT Pを使用する場合、データ接続でTLSセッション再開を要求する

があり、両方にチェックが入っているのが推奨されています。
PROT Pの意味もわからず、下の欄のチェックを外したところ、
Explicitでは通信できました。

**Comment by sayurin** [comment]
[Win32/Win64 OpenSSL](https://slproweb.com/products/Win32OpenSSL.html)からダウンロードできるバイナリをFileZilla Serverのものと置き換えてみましたが、FileZilla Serverを起動できませんでした。どうやら自分でFileZilla Serverをビルドし直す必要がありそうです。

もしくは既に書かれていますが、**PROT Pを使用する場合、データ接続でTLSセッション再開を要求する**のチェックを外すことです。

**Comment by sayurin** [comment]
得られた情報を[互換性](https://github.com/ffftp/ffftp/wiki/Compatibility)に記載しました。

**Comment by jun1poko** [comment]
いろいろ調べてくださり、ありがとうございます。
FileZilla Serverのビルドが成功するかどうかはわかりませんが、
PROT P～のチェックを外し、Implicit接続は非対応としていこうと思います。

**Comment by sayurin** [comment]
@jun1poko Implicit接続はポート番号990に変更する必要があると思いますが、それでもつながらないのでしょうか？

**Comment by jun1poko** [comment]
遅くなってすみません。
990になっており、つながりません。
