### ISSUE TITLE
ローカルに無効なシンボリックリンクやジャンクションがあると、ミラーリングが始まらない

### ISSUE THREAD

**Issue by Phroneris** [ffftp/ffftp#166]
なんじゃそりゃって感じの話ですが。
ローカル側のどこか（ルート直下とは限らず）にシンボリックリンクまたはジャンクションがあり、そのリンク先のパスが削除済みなどで実在しない場合、ミラーリングアップロードや同ダウンロードの「処理内容表示」ボタンを押すと、そのダイアログが消えるまでは良いのですがその後何も始まらず、無反応に終わります。
エラーもヘルプ情報も無くて原因究明が大変だったので、少なくとも記録として残しておきます。

### 再現手順
1. 正常にミラーリングできるような、Webサイト用ローカル`C:\web`とホストが用意されているとする
1. 全く別のローカルフォルダ`C:\temp`を作成する
1. cmdから`mklink /J "C:\web\link" "C:\temp"`を実行して、ジャンクション`C:\web\link`を作成する（※ジャンクション作成なら管理者権限不要）
1. FFFTPで、ローカルに`C:\web`を指定する
1. 「ミラーリングアップロード」 > 「処理内容表示」を実行して、正常動作を確認する
1. 「キャンセル」を押して、転送/削除ファイル一覧を閉じる
1. ローカルフォルダ`C:\temp`を削除する
1. 手順5を再び行う

### 期待する挙動
- 「ミラーリングアップロードを開始します。」のダイアログが消える
- メイン画面下の処理内容ログが反応する（処理できないなら少なくともエラーを吐く）
- 転送/削除ファイル一覧のダイアログが表示される

### 実際の挙動
- 「ミラーリングアップロードを開始します。」のダイアログが消える
- メイン画面下の処理内容ログが**反応しない**（エラーすら吐かない）
- 転送/削除ファイル一覧のダイアログが**表示されない**

### 原因に気付く前にググったりして試したけど効果が無かったこと
- `index-unko.html`など、明らかにホスト側に無い（＝絶対にミラーリングアップロードされる）ようなファイルをローカルに作成
- 「環境設定」 > 「ミラーリング」 > 「転送しないファイル名」の一覧を全て削除
- 「環境設定」 > 「表示1」 > 「ファイルのタイムスタンプの秒単位を表示する」を有効化
- 「ホストの設定」 > ホストを選んで「設定変更」 > 「拡張」 > 「ホストのタイムゾーン」を「GMT」（±0:00）に変更
- 「ホストの設定」 > ホストを選んで「設定変更」 > 「高度」 > 上３つのオプションの色々な組み合わせ

### 環境
- FFFTP 64bit v4.4（設定は多分ほぼデフォルト）
- Windows 7 64bit

**Comment by sayurin** [comment]
報告ありがとうございます。直感的にはバグっぽいですが、ひとまずは。

「シンボリックリンクまたはジャンクションがあり、そのリンク先のパスが削除済みなどで実在しない」…ファイルが在るような無いような、扱いが難しいですね。そのファイルに対してはどう扱うのが妥当とお考えでしょうか？

**Comment by Phroneris** [comment]
現状ですと、原因がローカルのフォルダにあるのか、ホスト側にあるのか、FFFTPの環境設定にあるのか、あるいはローカルが内蔵ドライブか外付けドライブかの違いにあるのか等、自己解決のための手がかりが全然ありません。
また、無効なシンボリックリンク／ジャンクションが存在し放置されている状態というのは、FTPどうこう以前にデータ管理の面で、ユーザー側にとっては把握し修正しておきたい不適切な状態だと思います。
ですので、「これはローカルが悪いんやで」（できれば「これはこのフォルダにある無効なシンボリックリンク／ジャンクションが悪いんやで」）という感じのエラーを吐いて、正常に続行せず止まってくれれば嬉しいです。

といっても、あたかもそこにフォルダやファイルがあるかのようにソフトを騙すのがこれらの機能なので、それをソフト自身に検出させることができるのかどうかはよく存じませんが…。

**Comment by sayurin** [comment]
ま調査できていませんが、ミラーリングに限らず、アップロードなど全てのファイル操作に対策が必要そうですね。
ミラーリングから順に対処を考えていこうと思います。

**Comment by sayurin** [comment]
ディレクトリ一覧取得時に、リンク先のディレクトリが存在しない場合エラーが発生していました。エラー検出はしていましたが、一切メッセージを出していなかったので、ユーザーから見て何が起きたのか分からない作りになっていました。

そこら中のエラー処理は無視されていたり、適当に処理されているので、分かりづらいのはここだけじゃなさそうです…。

ひとまずログウィンドウにメッセージを表示するようにしました。
