### ISSUE TITLE
停止しました

### ISSUE THREAD

**Issue by masatakayama** [ffftp/ffftp#171]
主にアップロード直後に起きる気がします。

問題の署名:
  問題イベント名:	APPCRASH
  アプリケーション名:	ffftp.exe
  アプリケーションのバージョン:	4.4.0.0
  アプリケーションのタイムスタンプ:	5dda1e71
  障害モジュールの名前:	StackHash_66cf
  障害モジュールのバージョン:	6.1.7601.24535
  障害モジュールのタイムスタンプ:	5dc1e7f7
  例外コード:	c0000374
  例外オフセット:	00000000000bf232
  OS バージョン:	6.1.7601.2.1.0.768.3
  ロケール ID:	1041
  追加情報 1:	66cf
  追加情報 2:	66cf0119647c6bfc784f88dd20442f9a
  追加情報 3:	ce5f
  追加情報 4:	ce5f4b10559f71d8cb2d01df185b54de

問題の署名:
  問題イベント名:	APPCRASH
  アプリケーション名:	ffftp.exe
  アプリケーションのバージョン:	4.4.0.0
  アプリケーションのタイムスタンプ:	5dda1e71
  障害モジュールの名前:	StackHash_4ace
  障害モジュールのバージョン:	6.1.7601.24535
  障害モジュールのタイムスタンプ:	5dc1e7f7
  例外コード:	c0000374
  例外オフセット:	00000000000bf232
  OS バージョン:	6.1.7601.2.1.0.768.3
  ロケール ID:	1041
  追加情報 1:	4ace
  追加情報 2:	4ace16b8c4e0c68b615e66789c3dfa5f
  追加情報 3:	4b13
  追加情報 4:	4b1306f4e834eeddf9c2f43a93404f34

**Comment by sayurin** [comment]
報告ありがとうございます。 #122 と同件で、１バリエーションとして対応します。
