### ISSUE TITLE
ウィンドウのタイトルバーに、以前のように「ホストの設定名」を表示してください。

### ISSUE THREAD

**Issue by sugawarasapporo** [ffftp/ffftp#196]
同じホストでフォルダ単位でホストの設定を作成していて、 
「ホストの設定名」にフォルダ名を入れることで、効率よく作業が出来ていました。

よろしくお願いいたします。

**Comment by sayurin** [comment]
ホストの設定名が必要なのでしょうか？ 記述を読む限り、現在のフォルダ名が表示された方が有用に感じられますが、いかがでしょうか？

**Comment by sugawarasapporo** [comment]
そうですね。
フォルダ名が表示されていた方が便利ですね。
お願いいたします。

**Comment by sayurin** [comment]
念のためタイトルバーの表示項目の変遷を確認しました。

- [～2014/1/10；](https://github.com/ffftp/ffftp/blame/4d0ff566a1043fd0411a21f5d6097045e2d94ac8/main.c#L622) ホスト名、フィルタ文字列
- [2014/1/11～2016/7/22](https://github.com/ffftp/ffftp/blame/f8dc74e64bfd32eb561e76bc4f9435a82a012fbc/main.c#L949)； ホスト名、フィルタ文字列、暗号化方式
- [2016/7/23～2018/4/4](https://github.com/ffftp/ffftp/blame/27161f5f92cde260a444284609f8fcd059b56fe2/main.cpp#L774)； ユーザー名、ホスト名、フィルタ文字列、暗号化方式
- [2018/4/5～](https://github.com/ffftp/ffftp/blame/76616a9b842feaa1211871a64f974d47da1a2556/main.cpp#L752)； ホスト名、フィルタ文字列

という具合で原点回帰しています。ホスト名＝ホストの設定名であれば現在も表示されていますし、異なるのであれば過去に表示されていたことはなさそうです。確認ですが、ユーザー名を復活させてほしいという要望ではありませんよね？

**Comment by sugawarasapporo** [comment]
最新版にしたら　ホストの設定名　に戻っていました。

ありがとうございます。

**Comment by sayurin** [comment]
特にコードを変更したわけでもないのに

> 最新版にしたら　ホストの設定名　に戻っていました。

という表現をされることが気になっていました。

リファクタリングしている際にコードの微妙な違いに気づきました。OSS化当初から接続方法によって表示されるものが変わる仕様のようです。

ホスト一覧を使ってホストへ接続したとき → 設定名が表示される
https://github.com/ffftp/ffftp/blob/2bf85c03c1e059a2f75dbd48ef73be5961e12414/connect.c#L163

ホスト名を入力してホストへ接続したとき → アドレスが表示される
https://github.com/ffftp/ffftp/blob/2bf85c03c1e059a2f75dbd48ef73be5961e12414/connect.c#L242

指定したホスト名でホストへ接続したとき → アドレスが表示される
https://github.com/ffftp/ffftp/blob/2bf85c03c1e059a2f75dbd48ef73be5961e12414/connect.c#L414

ホストのヒストリで指定されたホストへ接続したとき → アドレスが表示される
https://github.com/ffftp/ffftp/blob/2bf85c03c1e059a2f75dbd48ef73be5961e12414/connect.c#L490

最後のパターン、ヒストリを使用した場合には設定名が表示されるべきなのかもしれません。
