### ISSUE TITLE
Windows 10 ProのIISで構築したFTPサイトに接続できません

### ISSUE THREAD

**Issue by kuron01** [ffftp/ffftp#200]
はじめまして。よろしくお願いします。
FFFTP Ver4.7を使用してWindows 10 ProのIISで構築したFTPサイトに接続できません。
メニューから「接続」を選択して、ホストの設定済みのホスト一覧から「接続」を押下すると、以下の表示がされて接続できません。
----------引用ここから----------
FTP over Explicit SSL/TLS (FTPIS)を使用します．
ホスト ○○○○ (xxx.xxx.xxx.xxx:21)に接続しています．
接続しました．
Certificate validation error: 800B0109.
接続できません．
FTP over Explicit SSL/TLS (FTPES)を使用します．
ホスト ○○○○ (xxx.xxx.xxx.xxx:21)に接続しています．
接続しました．
接続できません．
通信は暗号化されていません．
第三者にパスワードおよび内容を傍受される可能性があります．
ホスト ○○○○ (xxx.xxx.xxx.xxx:21)に接続しています．
接続しました．
接続できません．
----------引用ここまで----------
上記状態で応答が無くなってしまいます。
FTPサイトについてですが、SSL無しで基本認証で設定しております。
セキュリティソフトを無効にして、WindowsDefenderファイアウォールをすべて無効にしても同じ結果でした。
お忙しいところ大変恐縮ですが、ご確認をお願いいただけますでしょうか。

**Comment by sayurin** [comment]
参考までに他のftpクライアントからは接続可能でしょうか？

引用いただいた接続ログによりますと、TCP/IP的にはサーバーと接続できています。接続しますと、通常であればサーバーから`220 Service ready`を受信しますが、それがないままTCP/IPの切断を受けています。

> セキュリティソフトを無効にして、WindowsDefenderファイアウォールをすべて無効にしても同じ結果

とのことですが、サーバーもしくはクライアント側に何らか切断するソフトウェアが動作している可能性があります。

**Comment by kuron01** [comment]
>>sayurin
返信ありがとうございます。
WinSCPをインストールして試したところ、接続できませんでした。
FTPクライアントではなくFTPサーバー側の問題のようです。大変失礼いたしました。
WindowsUpdateが原因のように思われますので、確認いたします。
お忙しいところ申し訳ありませんでした。

**Comment by sayurin** [comment]
後学のため、切断された原因が特定できましたら教えてください。
