### ISSUE TITLE
htmlヘルプのファイルがgit clone以外でダウンロードしたときに壊れているようです

### ISSUE THREAD

**Issue by sntulix** [ffftp/ffftp#205]
* ケース
  * git cloneしたFFFTP.CHM・・・ページを見れます。
  * リリースされているzipにあるffftp.chm・・・目次は出ますが、ページが出ません。
  * コミットヒストリーにあるffftp.chm・・・目次は出ますが、ページが出ません。

* 試した環境
  * windows 10 Pro 1903 (ビルド18362.900)

よろしくお願いします。

**Comment by sayurin** [comment]
インターネットからダウンロードしたコンテンツについては、ダウンロード時および解凍時にファイルに対してマークが付けられ、保護機能が働きます。画像は英語版Windowsですが、ファイルのプロパティから黄色でマーカーした部分、保護解除する必要があります。ここを確認していただけますでしょうか？
 ![image](https://user-images.githubusercontent.com/3615855/86595164-47b0df80-bfd3-11ea-98df-2b56fa8dc736.png)

この動作は、ダウンロードツール及び解凍ツールのセキュリティ機能ですので、ffftp及びヘルプビューア側では制御できません。
また、MSI版であれば、正式なインストール手順を経ているため、保護もかからないようになっています。

**Comment by sntulix** [comment]
ひらけました！
覚えました。
丁寧なガイドをありがとうございました
