### ISSUE TITLE
ミラーリングアップロードが動きません

### ISSUE THREAD

**Issue by taraimo** [ffftp/ffftp#209]
windows10でFFFTP Ver 4.7を使用してます。
サーバに空のフォルダーを作って、PCに同じ名前のフォルダーに5つくらい小さなテキストファイルを入れて ミラーリングアップロードをすると、処理が固まってキャンセル・強制終了しても戻ってきません。
やめさせるには、タスクマネージャーで終了しか方法がありません。
ファイルは転送されてなく、ホストを変えても同じでした。
お手数お掛けしますが、調査をお願いします。

**Comment by pa100-100** [comment]
同じ様な状況ですので、下記します。
使用環境は、win10 64bitでFFFTPはv4.7(64bit版)。
1.コマンドメニューのミラーリングアップロードをクリック。
2.[処理内容表示]クリック。
3.正常に「一覧表」が表示される。
4.[実行]をクリックするも、それ以上進まない。
右上の[Ｘ］をクリックすると、「ファイル転送中です。」が出るが、そこの[強制終了]も効かない。
タスクマネージャーの[タスクの終了]で、終了。
サブフォルダーでも同様にNG。
ファイルを1つずつ選択してのアップロードは可能。
FFFTPは以前から使わせていただいており、win7までは問題なく快適でしたが、win10（v2.00→v4.7）になってからミラーリングアップロードがうまくいきません（v2.00では不具合状況が上記とはちょっと異なっていましたが）。
当方での対応方法やBug Fix等、よろしくお願いいたします。

**Comment by sayurin** [comment]
@taraimo  @pa100-100   通常のアップロードは動作するのでしょうか？

**Comment by pa100-100** [comment]
通常のアップロード（アップロードするファイルを選択し、コマンドメニューの上矢印ボタンをクリック）は正常に動作します。

**Comment by taraimo** [comment]
アップロードは数量関係無しにファイルでもフォルダーごとでも、ドラックアンドドロップしても正常に動作してます。

**Comment by umasipotato** [comment]
こちらの環境 Windows10 64bit Pro <-> Ftp Server Pro (Android9/ZenFone Max Pro M1)
PCとスマフォをミラーリングアップロードで同期してます。
FFTPのV4.6からミラーリングアップロードが機能しなくなりました。
現象としては転送ダイアログが出ないまま待たされて、終了も強制終了もできなくなる。

FFFTP Ver 4.5:動作する
FFFTP Ver 4.6:動作しない
FFFTP Ver 4.7:動作しない

たぶん4.6で何か不具合が入ってます

**Comment by sayurin** [comment]
参考： [v4.5とv4.6の差分](https://github.com/ffftp/ffftp/compare/v4.5...v4.6)

**Comment by pa100-100** [comment]
@sayurin 
x64-Release-ffftpにてミラーリング アップロードが問題無く動作するようになりました。
ありがとうございました。
Mirroring uploads now work fine with x64-Release-ffftp.
Thank you very much.

**Comment by taraimo** [comment]
ミラーリングアップロード動作確認できました。
対応して頂き、ありがとうございました。
Thank you very very much!
