### ISSUE TITLE
SAKURA Internet サーバ接続時の例外（ 0xc0000409）発生　FFFTP ver.4.7

### ISSUE THREAD

**Issue by fj74c35xdk9w5e** [ffftp/ffftp#215]
エディション　Windows 10 Pro
バージョン　20H2
OS ビルド　19042.685

FFFTP v4.7 でSAKURA Internet サーバ上に接続しようとすると例外が発生します。
※イベントビューアのログ

障害が発生しているアプリケーション名: ffftp.exe、バージョン: 4.7.0.0、タイム スタンプ: 0x5eb62593
障害が発生しているモジュール名: ffftp.exe、バージョン: 4.7.0.0、タイム スタンプ: 0x5eb62593
例外コード: 0xc0000409
障害オフセット: 0x0000000000143841
障害が発生しているプロセス ID: 0x42dc

FFFTP v2.00 では、いまでも問題無く接続できます。

FFFTP v4.7の場合は何らかの設定変更などが必要でしょうか。
御教示いただけると幸いです。
よろしくお願いします。

**Comment by fj74c35xdk9w5e** [comment]
※追加
FFFTP ver.3.2 64bit では 例外: 0xc0000409 が発生すること無く接続できます。

**Comment by fj74c35xdk9w5e** [comment]
※追加
FFFTP ver.3.2 64bit 及び ver.4.0 64bit では 例外: 0xc0000409 が発生すること無く接続できます。

FFFTP ver.4.5 64bit 及び ver.4.7 64bit では 例外: 0xc0000409 が発生しました。

**Comment by sayurin** [comment]
SAKURA Internetの具体的にはどのサービスでしょうか？ また「接続しようと」とはより具体的にどのタイミングか説明可能でしょうか？
差し支えなければftpサーバ名（id / passは含まない）を教えていただくことは可能でしょうか。というのもログイン前に発生するエラーであれば、id / pass無しでもこちらで再現可能なので、調査が進みます。

**Comment by sayurin** [comment]
参考： [v4.0とv4.5との差分](https://github.com/ffftp/ffftp/compare/v4.0...v4.5)
といってもこれだけではすぐにはわかりませんが。

**Comment by fj74c35xdk9w5e** [comment]
SAKURA Internetのレンタルサーバに FFFTP v4.7で接続しようとした際に、

211 End
>>CD C:\Users\########\Documents\########\www
>CWD /home/########/www
250 CWD command successful
>XPWD
257 "/home/########/www" is the current directory
>TYPE A
200 Type set to A
>PASV
227 Entering Passive Mode (202,###,##,##,232,66).
ダウンロードのためにホスト 202.###.##.## (59458) に接続しています. (TCP/IPv4)
接続しました.
>LIST
150 Opening ASCII mode data connection for file list

のタイミングで終了します。

**Comment by fj74c35xdk9w5e** [comment]
＞参考： v4.0とv4.5との差分
＞といってもこれだけではすぐにはわかりませんが。

v4.0 で問題無く接続できて v4.5 で例外発生なので、その間のバージョンに境界がありそうだとは言えると思います。具体的にどのバージョンまではわかりませんが。
当方としても、その間の v4.1, v4.2, v4.3, v4.4 までテストしている時間的余裕がありません。その点はご理解願います。

**Comment by fj74c35xdk9w5e** [comment]
v4.3、v4.4 で既存のレジストリを取り込んで接続を試みましたが

※v4.3 の場合は接続できました。下記のところまで動作します。
接続しました. (TCP/IPv4)
>LIST
150 Opening ASCII mode data connection for file list
226 Transfer complete
ファイル一覧の取得は正常終了しました. (5227 Bytes)
 
---------------

※v4.4 の場合、下記のタイミングで FFFTP v4.4が終了します。
>LIST
150 Opening ASCII mode data connection for file list

**Comment by sayurin** [comment]
ありがとうございます。 [v4.3とv4.4](https://github.com/ffftp/ffftp/compare/v4.3...v4.4) の変更点で、 ログイン後の `LIST` コマンド実行後ということですね。また、 [レンタルサーバ](https://www.sakura.ne.jp/) とのこと、２週間のお試しが可能なのでこちらでも再現してみようと思います。

**Comment by sayurin** [comment]
> 障害オフセット: 0x0000000000143841

これは[ `abort` 関数](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/abort?view=msvc-160)の中を指していたので、問題個所の特定にはつながりませんでした。

**Comment by sayurin** [comment]
@fj74c35xdk9w5e  `/home/########/www` ディレクトリに特殊な名前のファイルが配置されていたりしますでしょうか？ その場合、ファイル名の文字コードを自動判別から別の設定に変更した場合に停止しなくなるでしょうか？

**Comment by fj74c35xdk9w5e** [comment]
/home/########/www ディレクトリでは、確かにファイル名が文字化けしたものが１つありました。

試しに、ホストの設定でファイル名の漢字コードを EUC に変えたところ、前述のファイル名が正しく表示されるようです。
ホストの設定でファイル名の漢字コードを EUC にした状態で、FFFTP Ver 4.3上でこのファイルを削除しました。
その結果、FFFTP Ver 4.7でも LISTコマンドでのエラーは発生しません。

このファイルが原因ですね。

たいへんお騒がせ致しました。
御教示いただき誠にありがとうございました。

**Comment by sayurin** [comment]
@fj74c35xdk9w5e ありがとうございます。 #204 でファイル名に問題があった場合でも処理継続できるよう改善予定です。
