### ISSUE TITLE
FC2 Web フォルダ／ファイル名、タイムスタンプの年、サイズ表示不具合 (FFFTP v4.8)

### ISSUE THREAD

**Issue by fj74c35xdk9w5e** [ffftp/ffftp#223]
エディション　Windows 10 Pro
バージョン　20H2
OS ビルド　19042.685

FFFTP v4.7 / v4.8 で FC2 Web サーバーに接続した場合、v4.8では サーバー（ホスト）側のフォルダ／ファイル名とタイムスタンプの「年」、サイズの表示がおかしくなるようです。

（例）
※FFFTP v4.7 64bit の場合
名前(フォルダ)  日付
img                  2020/08/03 12:45
old                   2016/11/04
resource           2017/10/06

名前(ファイル)  日付                         サイズ
link.html           2017/10/20               3,114
menu.html       2013/05/13               3,427
access.html      2020/07/16 18:05     5,589
index.html        2020/08/03 13:01   12,003
service.html      2017/10/26             11,106

※FFFTP v4.8 64bit の場合
名前(フォルダ)   日付
img                     4096/08/03 12:45
2016 old             4096/11/04
2017 resource    4096/10/06

名前(ファイル)       日付                       サイズ
2017 link.html        3114/10/20             10,014
2013 menu.html    3427/05/13             10,014
access.html            5589/07/16 18:05   10,014
index.html             2020/08/03 13:01   12,003
service.html           2017/10/26             11,106

![ffftp_v47_v48_fc2](https://user-images.githubusercontent.com/76546203/103449425-8fe35d00-4ceb-11eb-91e7-7070edfeed77.jpg)

**Comment by sayurin** [comment]
@fj74c35xdk9w5e すみません。メニューにある「ファイル一覧をビューアで表示」で表示される内容もいただけますか？

**Comment by fj74c35xdk9w5e** [comment]
「ファイル一覧をビューアで表示」の表示は下記の通りです。
※v4.7 / v4.8 で差はありません（Win10  の fc /b で比較済み）

drwxr-xr-x   7 syouwaky 10014        4096 Oct 14 06:48 .
drwxr-xr-x   7 syouwaky 10014        4096 Oct 14 06:48 ..
-rw-r--r--   1 syouwaky 10014        5472 Nov 24  2018 access_20181124.html
-rw-r--r--   1 syouwaky 10014        5589 Jul 16 18:05 access.html
-rw-r--r--   1 syouwaky 10014       18299 Mar 11  2019 apple-touch-icon.png
-rw-r--r--   1 syouwaky 10014        4587 Mar 11  2019 cal_20190311.html
-rw-r--r--   1 syouwaky 10014        4742 Jan  7  2020 cal.html
-rw-r--r--   1 syouwaky 10014        3753 Oct 26  2017 contact.html
-rw-r--r--   1 syouwaky 10014       67646 Mar 11  2019 favicon.ico
-rw-r--r--   1 syouwaky 10014          53 Dec 13  2014 googlec280c74000c4f070.html
-rw-r--r--   1 syouwaky 10014         760 Oct 26  2017 .htaccess
drwxr-xr-x   2 syouwaky 10014        4096 Apr  7  2012 i
drwxr-xr-x   3 syouwaky 10014        4096 Aug  3 12:45 img
-rw-r--r--   1 syouwaky 10014       12003 Aug  3 13:01 index.html
-rw-r--r--   1 syouwaky 10014        3114 Oct 20  2017 link.html
-rw-r--r--   1 syouwaky 10014        3427 May 13  2013 menu.html
drwxr-xr-x   2 syouwaky 10014        4096 Nov  4  2016 old
drwxr-xr-x   2 syouwaky 10014        4096 Oct  6  2017 resource
-rw-r--r--   1 syouwaky 10014       11106 Oct 26  2017 service.html
-rw-r--r--   1 syouwaky 10014        3688 May 26  2013 sitemap.html
-rw-r--r--   1 syouwaky 10014        1607 Nov  3  2017 sitemap_pc.xml
-rw-r--r--   1 syouwaky 10014        2735 Dec  5  2018 sitemap.xml
drwxr-xr-x   4 syouwaky 10014        4096 Oct 14 06:48 sp
-rw-r--r--   1 syouwaky 10014        5166 Oct 20  2017 style.css

**Comment by sayurin** [comment]
情報ありがとうございます！

**Comment by sayurin** [comment]
### 状況整理

```
0          1 2        3     4    5   6  7     8
-------------------------------------------------------
drwxr-xr-x 7 syouwaky 10014 4096 Oct 14 06:48 .
drwxr-xr-x 7 syouwaky 10014 4096 Oct 14 06:48 ..
-rw-r--r-- 1 syouwaky 10014 5472 Nov 24 2018 access_20181124.html
```

というフォーマットですが、3桁目、グループ名がないためにグループIDとして数値になっています。これに対して、

https://github.com/ffftp/ffftp/blob/089dd3a7f5483b366fd502714430aa5cb65ebbb1/filelist.txt#L48-L51

LIST_UNIX_14フォーマットでマッチしていました。なぜかというと

https://github.com/ffftp/ffftp/blob/089dd3a7f5483b366fd502714430aa5cb65ebbb1/filelist.txt#L58-L61

のようにグループIDを出力しないフォーマットも存在するためスキップ処理があるため

- 3桁目： グループID → ファイルサイズ
- 4桁目： ファイルサイズ → 年（1600-9999で判定）
- 5桁目： 月
- 6桁目： 日
- 7桁目以降： 年 → ファイル名（空白有）

という解釈です。


### 対策

年 月 日 フォーマットを持つLIST_UNIX_14のパターンを分離して優先度を下げるとかですかね。

年の範囲を狭める手もありますが、

```
-rw-r--r-- 1 syouwaky 10014 1607 Nov 3 2017 sitemap_pc.xml
```

のように年に見えるファイルサイズはどうしようもないですし。

**Comment by sayurin** [comment]
@fj74c35xdk9w5e  こちらにある、x64-Release-ffftp で改善されるか確認いただくことは可能でしょうか？（サイズ大きくてすみません。バージョン番号は更新されていないので取り違えないようにご注意願います。）
https://github.com/ffftp/ffftp/actions/runs/458980772

**Comment by fj74c35xdk9w5e** [comment]
x64-Release-ffftp　を実行してみました。
LISTコマンドで年が無い場合、時刻がファイル名の列に表示されるようですね。

![ffftp_test_20210104_0826_LIST](https://user-images.githubusercontent.com/76546203/103491599-93e8b980-4e68-11eb-925d-dd1e141fbe97.jpg)

**Comment by fj74c35xdk9w5e** [comment]
「ファイル一覧をビューアで表示」の表示は変わっていませんが念のため

drwxr-xr-x   7 syouwaky 10014        4096 Oct 14 06:48 .
drwxr-xr-x   7 syouwaky 10014        4096 Oct 14 06:48 ..
-rw-r--r--   1 syouwaky 10014        5472 Nov 24  2018 access_20181124.html
-rw-r--r--   1 syouwaky 10014        5589 Jul 16 18:05 access.html
-rw-r--r--   1 syouwaky 10014       18299 Mar 11  2019 apple-touch-icon.png
-rw-r--r--   1 syouwaky 10014        4587 Mar 11  2019 cal_20190311.html
-rw-r--r--   1 syouwaky 10014        4742 Jan  7  2020 cal.html
-rw-r--r--   1 syouwaky 10014        3753 Oct 26  2017 contact.html
-rw-r--r--   1 syouwaky 10014       67646 Mar 11  2019 favicon.ico
-rw-r--r--   1 syouwaky 10014          53 Dec 13  2014 googlec280c74000c4f070.html
-rw-r--r--   1 syouwaky 10014         760 Oct 26  2017 .htaccess
drwxr-xr-x   2 syouwaky 10014        4096 Apr  7  2012 i
drwxr-xr-x   3 syouwaky 10014        4096 Aug  3 12:45 img
-rw-r--r--   1 syouwaky 10014       12003 Aug  3 13:01 index.html
-rw-r--r--   1 syouwaky 10014        3114 Oct 20  2017 link.html
-rw-r--r--   1 syouwaky 10014        3427 May 13  2013 menu.html
drwxr-xr-x   2 syouwaky 10014        4096 Nov  4  2016 old
drwxr-xr-x   2 syouwaky 10014        4096 Oct  6  2017 resource
-rw-r--r--   1 syouwaky 10014       11106 Oct 26  2017 service.html
-rw-r--r--   1 syouwaky 10014        3688 May 26  2013 sitemap.html
-rw-r--r--   1 syouwaky 10014        1607 Nov  3  2017 sitemap_pc.xml
-rw-r--r--   1 syouwaky 10014        2735 Dec  5  2018 sitemap.xml
drwxr-xr-x   4 syouwaky 10014        4096 Oct 14 06:48 sp
-rw-r--r--   1 syouwaky 10014        5166 Oct 20  2017 style.css

**Comment by NORIYUKI1949** [comment]
同じ現象です。アンインストールして、Ver.4.7 の戻すと正常に表示されます。

**Comment by sayurin** [comment]
@NORIYUKI1949 v4.7 / v4.8どちらでも構いませんので、メニューにある「ファイル一覧をビューアで表示」で表示される内容を提供いただくことは可能ですか？

**Comment by NORIYUKI1949** [comment]
v4.7 の「ファイル一覧をビューアで表示」で表示される内容を添付いたします
![SnapCrab_NoName_2021-1-20_12-49-50_No-00](https://user-images.githubusercontent.com/44204497/105125468-cad4f580-5b1f-11eb-8034-a06e98ad684a.png)
v4.7
![SnapCrab_NoName_2021-1-19_14-59-57_No-00](https://user-images.githubusercontent.com/44204497/105125530-f48e1c80-5b1f-11eb-8e19-7a28947bc1f3.png)
v4.8
![SnapCrab_NoName_2021-1-19_14-41-22_No-00](https://user-images.githubusercontent.com/44204497/105125576-0cfe3700-5b20-11eb-9d48-2fc7a184050d.png)
