### ISSUE TITLE
ホスト名のDNSによる名前解決がIPv6だけの場合、FFFTPは名前解決ができず、接続できない。

### ISSUE THREAD

**Issue by t2750ffftp** [ffftp/ffftp#226]
ホスト名のDNSによる名前解決がIPv6だけの場合、FFFTPは名前解決ができず、接続できない。

FFFTPのホストの設定で、FQDNのホスト名で、名前解決がIPv6だけの場合、名前解決できずに接続できません。
Issues に「 IPv6対応の改善 #11 」（ラベルの「enhancement」）という登録がありますが、マイクロソフトのサイトのドキュメントを見ると、ホスト名の名前解決のための getaddrinfo の使い方が正しくないように推察されます。
FFFTPのコードが、インライン展開されるコードで良くわからないので、ズバリのパッチを提案できなくて恐縮です。

## マイクロソフトのWinSockのドキュメントでは、アドレス・ファミリー AF_UNSPEC で、IPv4 と IPv6 の両方を名前解決できるとは言っていない。

マイクロソフト以外のインターネットのサイトで、ホスト名の名前解決で、「プロトコル・ファミリーで AF_UNSPEC を指定すれば、IPv4 と IPv6 のいずれでも名前解決できる」と書いてあるのを見かけますが、以下のマイクロソフトのサイトを見る限り、そのようなことは、一言もありません。
マイクロソフトのサイトでは、タイプが SOCK_STREAM か SOCK_DGRAM の場合は、アドレス・ファミリーは、 AF_INET or AF_INET6 を指定するように記述されています。AF_UNSPEC が指定できるとは記述されていません。

https://docs.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-socket

以下、マイクロソフトのサイトから、抜粋引用。

> type
> 
> SOCK_STREAM
> A socket type that provides sequenced, reliable, two-way, connection-based byte streams with an OOB data transmission mechanism. 
> This socket type uses the Transmission Control Protocol (TCP) for the Internet address family (AF_INET or AF_INET6).
> 
> SOCK_DGRAM
> A socket type that supports datagrams, which are connectionless, unreliable buffers of a fixed (typically small) maximum length. 
> This socket type uses the User Datagram Protocol (UDP) for the Internet address family (AF_INET or AF_INET6). 

> ---
> In Windows Sockets 1.1, the only possible socket types are SOCK_DGRAM and SOCK_STREAM.

## FFFTPの関連コード

https://github.com/ffftp/ffftp/blob/5384b6eb7c1edff70530bece566dc95a9bc2d457/connect.cpp#L1806-L1833

https://github.com/ffftp/ffftp/blob/5384b6eb7c1edff70530bece566dc95a9bc2d457/connect.cpp#L2034-L2068

アドレス・ファミリーで AF_INET6 を指定しているところがなく、IPv6 の名前解決ができない。

## 不具合

以下のドメイン名やIPアドレスは、文書用のものに書き換えています。（実際のドメイン名やIPアドレスではありません。）

#### IPv6のサブドメインのDNSの設定

$ORIGIN     ipv6.example.jp.
== 割愛 ==
foobar  AAAA  2001:db8::1

FFFTPの設定画面「ホストの設定」のタブ「基本」の「ホスト名（アドレス）」が、foobar.ipv6.example.jp だど、名前解決できず、接続できない。
ホスト名ではなく、アドレス　2001:db8::1 だと、名前解決は不要で、接続できる。

ホスト名

#### IPv4のサブドメインのDNSの設定

$ORIGIN     ipv4.example.jp.
== 割愛 ==
foobar  A  192.0.2.1

FFFTPの設定画面「ホストの設定」のタブ「基本」の「ホスト名（アドレス）」が、foobar.ipv4.example.jp だど、名前解決でき、接続できる。

## 簡単なWinSockの名前解決のコードによるテスト結果

以下のコマンド・ラインの簡単なコードで、getaddrinfoで名前解決のテストをした結果
実行環境　Win 10 Pro / Visual Studio Community版 2019

コード途中の★印の部分

AF_UNSPEC または AF_INET
foobar.ipv4.example.jp（アドレスがIPv4）なら、名前解決できる
foobar.ipv6.example.jp（アドレスがIPv6）なら、名前解決できない。

AF_INET6
foobar.ipv4.example.jp（アドレスがIPv4）なら、名前解決できない。
foobar.ipv6.example.jp（アドレスがIPv6）なら、名前解決できる。

// テスト・コード
```
#pragma comment( lib, "ws2_32.lib" )

#include <iostream>
#include <winsock2.h>
#include <ws2tcpip.h>

int main( int argc, char *argv[])
{

	const char* hostname;
	struct addrinfo hints, * res, *res2;
	int rc;

	if (argc != 2) {
		std::cout << "No hostname\n";
		return 1;
	}

	hostname = argv[1];

	std::cout << hostname;
	std::cout << "\n";

	WSADATA data;
	rc = WSAStartup(MAKEWORD(2, 0), &data);
	if (rc != 0) {
		std::cout << "ERROR: WSAStartup (RC=" << rc << ")\n";
		return 1;
	}

	memset(&hints, 0, sizeof(hints));
	//hints.ai_socktype = SOCK_STREAM;
	hints.ai_family = AF_UNSPEC;　　　・・・　★　ホスト名の名前解決がIPv4なら名前解決できる。IPv6はできない。
	//hints.ai_family = AF_INET;　　　・・・　★　ホスト名の名前解決がIPv4なら名前解決できる。IPv6はできない。
	//hints.ai_family = AF_INET6;　　　・・・　★　ホスト名の名前解決がIPv4は名前解決できない。IPv6はできる。

	rc = getaddrinfo(hostname, NULL, &hints, &res);
	if (rc != 0) {
		std::cout << "ERROR: getaddrinfo (RC=" << rc << ")\n" ;
		return 1;
	}

    std::cout << "OK\n";

	for (res2 = res; res2 != NULL; res2 = res2->ai_next) {

		LPSOCKADDR sa;
		TCHAR ipaddr[64];
		DWORD ipaddrlen;
		char c[2];
		DWORD i;

		sa = (LPSOCKADDR) res2->ai_addr;

		memset(ipaddr, 0, sizeof(ipaddr));
		ipaddrlen = sizeof(ipaddr);

		rc = WSAAddressToString(sa, (DWORD)res2->ai_addrlen, NULL, ipaddr, &ipaddrlen);
		if (rc != 0) {
			std::cout << "ERROR: WSAAddressToString (RC=" << rc << ")\n";
			return 1 ;
		}
		std::cout << ipaddrlen << "\n";

		switch (res2->ai_family) {
		case AF_INET:
			std::cout << "IPv4: " ;
			break;
		case AF_INET6:
			std::cout << "IPv6: " ;
			break;
		}

		for (i = 0; i < ipaddrlen; i++) {
			c[0] = (char) ipaddr[i];
			c[1] = 0;
			std::cout << c;
		}
		std::cout << "\n";

	}

	WSACleanup();

}
```

**Comment by sayurin** [comment]
いくつか話題が混ざっているように見えます。

---

`SOCK_STREAM`、`SOCK_DGRAM`はわかりづらいですが、前者はTCP、後者UDPを指します。ftpにおいては常にTCPを使用します。

---

WinSockのバージョンはWindows 95 OSR2以降、常に2.2です。1.1は16bit時代の値ですので考慮していません。

https://docs.microsoft.com/en-us/windows/win32/api/winsock/nf-winsock-wsastartup#remarks

> Windows Sockets version 2.2 is supported on Windows Server 2008, Windows Vista, Windows Server 2003, Windows XP, Windows 2000, Windows NT 4.0 with Service Pack 4 (SP4) and later, Windows Me, Windows 98, and Windows 95 OSR2. Windows Sockets version 2.2 is also supported on Windows 95 with the Windows Socket 2 Update. Applications on these platforms should normally request Winsock 2.2 by setting the wVersionRequested parameter accordingly.
> 
> On Windows 95 and versions of Windows NT 3.51 and earlier, Windows Sockets version 1.1 is the highest version of the Windows Sockets specification supported.

---
IPv6で名前解決することと、IPv6で通信することは別問題です。`socket`関数で`AF_UNSPEC`を指定している点は、[Dual-Stack Sockets](https://docs.microsoft.com/en-us/windows/win32/winsock/dual-stack-sockets)という機能を使用しています。
本来、IPv4で通信する際には`socket`関数に`AF_INET`を渡し、IPv6で通信する際には`socket`関数に`AF_INET6`を渡す必要がありますが、`AF_UNSPEC`を渡すことでIPv4 / IPv6どちらであっても使用できるSOCKETが作成できます。

---
最後に本題ですが、`getaddrinfo`に`AF_INET6`でなく`AF_UNSPEC`を指定している点ですが、こちらは
https://docs.microsoft.com/en-us/windows/win32/api/ws2tcpip/nf-ws2tcpip-getaddrinfo#remarks

> A value of AF_UNSPEC for ai_family indicates the caller will accept any protocol family. This value can be used to return both IPv4 and IPv6 addresses for the host name pointed to by the pNodeName parameter. 

という記述に基づく処理で、`getaddrinfo`に`AF_UNSPEC`を渡した場合は、OSの設定に従いIPv4 / IPv6両方のアドレスが返されます。同ページにあるサンプルコードでも`AF_UNSPEC`を渡したうえで、IPv4 / IPv6の値が得られています。

---
`getaddrinfo`に`AF_UNSPEC`を渡した場合にIPv6のアドレスが得られない点についてはもう少し調べます。

**Comment by sayurin** [comment]
それとは別に、Windows XP対応を収束させるため、Windows Vistaから登場した [`WSAConnectByName`](https://docs.microsoft.com/en-us/windows/win32/winsock/function-calls-2#wsaconnectbyname) に切り替えることも検討しています。

**Comment by sayurin** [comment]
手元の環境で [getaddrinfoのExample Code](https://docs.microsoft.com/en-us/windows/win32/api/ws2tcpip/nf-ws2tcpip-getaddrinfo#example-code) を実行してみたところ `www.google.com` のアドレスとして

```
Calling getaddrinfo with following parameters:
        nodename = www.google.com
        servname (or port) =

getaddrinfo returned success
getaddrinfo response 1
        Flags: 0x0
        Family: AF_INET6 (IPv6)
        IPv6 address 2404:6800:4004:80d::2004
        Socket type: SOCK_STREAM (stream)
        Protocol: IPPROTO_TCP (TCP)
        Length of this sockaddr: 28
        Canonical name: (null)
getaddrinfo response 2
        Flags: 0x0
        Family: AF_INET (IPv4)
        IPv4 address 172.217.25.228
        Socket type: SOCK_STREAM (stream)
        Protocol: IPPROTO_TCP (TCP)
        Length of this sockaddr: 16
        Canonical name: (null)
```

IPv6 → IPv4 の順で値が返されました。nslookupでも同様の結果が得られました。

**Comment by sayurin** [comment]
@t2750ffftp 次の３コマンドでIPv6 / IPv4両方が得られるかを確認していただけますか？

- `nslookup www.google.com`
  デフォルトのDNSでクエリ
- `nslookup www.google.com 8.8.8.8`
  Google Public DNSでクエリ
- `nslookup www.google.com 2001:4860:4860::8888`
  Google Public DNSのIPv6でクエリ

https://developers.google.com/speed/public-dns/docs/using#addresses

**Comment by t2750ffftp** [comment]
ご返答、ありがとうございます。

まず初めに、そちらの環境では問題ないとのことであれば、当方のPCの問題のようですので、本件は無効としてクローズして下さい。
貴重なお時間をとらせてしまったこと、お詫びいたします。
FFFTPを含め、いろいろなフリー・ソフトを利用しており、それらには感謝しております。

残念ながら、私の Windows PC では、Windows 標準の ping -6 や nslookup で、IPv6 のみのFQDNのホスト名が扱えても、FFFTP は、画面下のログ表示部分に「ホスト foobar.ipv6.example.jp が見つかりません。」と表示されます。
設定登録で、ホスト名ではなく、IPv6のIPアドレスを指定すれば動作するので、著しい不都合があるわけではありませんので、繰り返しになりますが、当方のPCの問題ということで、ご放念下さい。
ありがとうございました。

いただきましたご返答については、以下のとおり、ご回答申し上げます。

> いくつか話題が混ざっているように見えます。
> SOCK_STREAM、SOCK_DGRAMはわかりづらいですが、・・・・
  == 省略 ==
> IPv6で名前解決することと、IPv6で通信することは別問題です。

理解しています。
件名の「・・・、接続できない」が誤解されるような投稿ですみません。
名前解決でアドレスが得られないので、結果として、接続できない、という趣旨です。
名前解決できた後の socket / connect には、いっさい触れておりません。
最初の投稿に記載しましたとおり、FFFTPの設定登録で、ホスト名ではなくIPv6のアドレスを指定を指定すれば接続できます。

> 同ページにあるサンプルコードでもAF_UNSPECを渡したうえで、IPv4 / IPv6の値が得られています。

ご連携いただきましたマイクロソフトのサイトは、確認しました。
マイクロソフトのサイトのサンプル・コードの getaddrinfo に関する部分は、私が試したテスト・コードと根幹はかわりありません。
最初の投稿する前に、
    hints.ai_family = AF_UNSPEC;
    hints.ai_socktype = SOCK_STREAM;
    hints.ai_protocol = IPPROTO_TCP;
アドレス・ファミリー以外のタイプとプロトコルを設定した動作も試していて、動作結果は同じでした。

確かに、原文で「 This value can be used to return both IPv4 and IPv6 addresses 」といっておりますが、
少なくとも、私の Windows PC で試した限りでは、そのようにはなりません。

Visual Studio Community 版は、ダウンロードして、標準のまま（特に、オプションの選択をせずに）インストールしただけなので、リンクされたライブラリが適切でない可能性もあります。

> 手元の環境で getaddrinfoのExample Code を実行してみたところ・・・
  == 省略 ==
> IPv6 → IPv4 の順で値が返されました。nslookupでも同様の結果が得られました。

ご参考までに、私のLAN環境（同じセグメント）にある Windows PC と Linuxマシンでの動作結果は以下のとおりでした。
なお、最初の投稿と同様、ドメイン名やIPアドレスは、文書用のものに書き換えています。

いただきましたご返答にある Windows の nslookup の第２パラメータで外部のDNSを指定ですが、当方は、PCのあるLANは、プロキシー経由でインターネット側へhttp(s)とftpのみアクセスできるようになっており、インターネット側へ直接通信はできないネットワークですので、PCから試すことはできません。（PCは、外部のDNSと直接通信はできません。）
本件の投稿にかかる PC と FFFTPの接続先のサーバーは、同一ＬANセグメントにあります。DNSサーバーは、到達可能な別セグメントにあります。（DNSサーバーは、当然、インターネット側と名前解決に関する直接通信ができます。）

◆ DNSの設定

DNSは、Linux で稼働している bind 9.16.5

◇IPv4のサブドメインのDNSの設定

$ORIGIN     ipv4.example.jp.
== 割愛 ==
foobar  A  192.0.2.1

◇IPv6のサブドメインのDNSの設定

$ORIGIN     ipv6.example.jp.
== 割愛 ==
foobar  AAAA  2001:db8::1

◇IPv4とIPv6の両方のサブドメインのDNSの設定（IPv4が先）

$ORIGIN     ipv4ipv6.example.jp.
== 割愛 ==
foobar  A  192.0.2.1
        AAAA  2001:db8::1

◇IPv4とIPv6の両方のサブドメインのDNSの設定（IPv6が先）

$ORIGIN     ipv6ipv4.example.jp.
== 割愛 ==
foobar  AAAA  2001:db8::1
        A  192.0.2.1

◆ Windows PC と Linuxマシン の nslookup による名前解決

◇ Windows PC のコマンド・プロンプト画面からの nslookup

foobar.ipv4.example.jp
Address: 192.0.2.1

foobar.ipv6.example.jp
Address: 2001:db8::1

foobar.ipv4ipv6.example.jp
Address: 2001:db8::1
         192.0.2.1

foobar.ipv6ipv4.example.jp
Address: 2001:db8::1
         192.0.2.1

◇ Linux マシンでの nslookup

foobar.ipv4.example.jp
Address: 192.0.2.1

foobar.ipv6.example.jp
Address: 2001:db8::1

foobar.ipv4ipv6.example.jp
Address: 192.0.2.1
Address: 2001:db8::1

foobar.ipv6ipv4.example.jp
Address: 192.0.2.1
Address: 2001:db8::1

◆  Windows PC と Linuxマシン の参照DNS

◇ Windows PC ( ipconfig /all )

== 割愛 ==
DNS サーバー. . . . . . . : 192.0.2.100　　　・・・ DHCPが返した当サイトのプライマリーDNS
                            192.0.2.101　　　・・・ DHCPが返した当サイトのセカンダリーDNS

◇ Linuxマシン ( cat /etc/resolv.conf )

search example.jp
nameserver 192.0.2.100
nameserver 192.0.2.101

◆ Windows PC と Linuxマシン のテスト・プログラムの getaddinfo による名前解決（実機による動作結果）

Windows PC のテスト・プログラムは、最初の投稿に掲載したもの
Linuxマシンのテスト・プログラムは、後述
いずれも、getaddrinfo のパラメータは、同じです。

foobar.ipv4.example.jp （名前解決が、IPv4のアドレスのみ）

プロトコル・ファミリー　｜ Windows PC 　　　　　　　 ｜ Linux マシン
AF_UNSPEC 　　　　　　　｜ IPv4アドレス 　　　　　　 ｜ IPv4アドレス
AF_INET 　　　　　　　　｜ IPv4アドレス 　　　　　　 ｜ IPv4アドレス
AF_INET6　　　　　　　　｜ 名前解決できない（正しい）｜ 名前解決できない（正しい）

foobar.ipv6.example.jp （名前解決が、IPv6のアドレスのみ）

プロトコル・ファミリー　｜ Windows PC 　　　　　　　 ｜ Linux マシン
AF_UNSPEC 　　　　　　　｜ 名前解決できない（★？★）｜ IPv6アドレス
AF_INET 　　　　　　　　｜ 名前解決できない（正しい）｜ 名前解決できない（正しい）
AF_INET6　　　　　　　　｜ IPv6アドレス　　　　　　　｜ IPv6アドレス

foobar.ipv4ipv6.example.jp （名前解決が、IPv4とIPv6の両方のアドレス）

プロトコル・ファミリー　｜ Windows PC 　　　　　　　 ｜ Linux マシン
AF_UNSPEC 　　　　　　　｜ IPv4アドレスのみ（★？★）｜ IPv4アドレス、IPv6アドレス
AF_INET 　　　　　　　　｜ IPv4アドレス　　　　　　　｜ IPv4アドレス
AF_INET6　　　　　　　　｜ IPv6アドレス　　　　　　　｜ IPv6アドレス

foobar.ipv6ipv4.example.jp （名前解決が、IPv4とIPv6の両方のアドレス）

プロトコル・ファミリー　｜ Windows PC 　　　　　　　 ｜ Linux マシン
AF_UNSPEC 　　　　　　　｜ IPv4アドレスのみ（★？★）｜ IPv4アドレス、IPv6アドレス
AF_INET 　　　　　　　　｜ IPv4アドレス　　　　　　　｜ IPv4アドレス
AF_INET6　　　　　　　　｜ IPv6アドレス　　　　　　　｜ IPv6アドレス

◆ = = = Linuxマシン の getaddrinfo による名前解決のテスト・コード = = =

#include <stdio.h>
#include <string.h>
#include <sys/socket.h>
#include <netdb.h>
#include <arpa/inet.h>

int main( int argc, char *argv[] )
{
	char *hostname ;
	char *service = "ftp" ;
	struct addrinfo hints, *resChainList, *res ;
	int  rc ;

	if ( argc != 2 ) {
		printf( "No hostname\n" ) ;
		return 1;
	}

	hostname = argv[1];

	printf( "%s\n", hostname ) ;

	memset( &hints, 0, sizeof(hints) ) ;
	//hints.ai_socktype = SOCK_STREAM;
	//hints.ai_family = PF_UNSPEC;
	hints.ai_family = AF_UNSPEC;
	//hints.ai_family = AF_INET;
	//hints.ai_family = AF_INET6;
	//hints.ai_protocol = IPPROTO_TCP;

	rc = getaddrinfo( hostname, NULL, &hints, &resChainList ) ;
	if ( rc != 0 ) {
		printf( "ERROR: getaddrinfo (RC=%d)\n", rc ) ;
		return 1;
	}
	printf( "OK\n" ) ;

	for ( res = resChainList ; res != NULL ; res = res->ai_next ) {

		char buf[64] ;
		memset( buf, 0, sizeof(buf) ) ;

		switch ( res->ai_family ) {
		case AF_INET:
			printf( "IPv4: " ) ;
			inet_ntop( res->ai_family, &((struct sockaddr_in *)res->ai_addr)->sin_addr, buf, sizeof(buf) ) ;
			break;
		case AF_INET6:
			printf( "IPv6: " ) ;
			inet_ntop( res->ai_family, &((struct sockaddr_in6 *)res->ai_addr)->sin6_addr, buf, sizeof(buf) ) ;
			break;
		default:
			printf( "UNKNOWN: " ) ;
			break ;
		}

		printf( "%s\n", buf ) ;

	}

}

**Comment by t2750ffftp** [comment]
本件は、試した範囲では、ある条件で名前解決できないことがわかりましたので、取り下げます。
その「ある条件」でも、名前解決できるほうがよい／名前解決できなくてよい、については、詳細な仕様・規定や他の条件の有無などを、全て把握・理解しているわけではないので意見は差し控えます。

実機確認した結果（私がテストした範囲）
Windowsのgetaddrinfoは、IPv6のリンク・ローカル・スコープだけのアドレスの場合、アドレス・ファミリーがAF_UNSPECだと名前解決でIPv6のアドレスを返さない。また、何か他にも条件がありそう（IPv6で到達不可能という条件がつきそう）ですが、ホスト名の名前解決がグローバル・スコープのIPv6のアドレスを持つ場合（IPv4とIPv6の両方を持っていても）、そのホスト名に対して名前解決できない。
これに対し、Windows標準のnslookup、Linuxのnslookupやプログラムによるgetaddrinfoは、DNSの設定どおりに名前解決する。

IPv6が主役になるのは、まだまだ、遠い先のことだと思いますし、そのころには、Windows側の実装もかわっているかもしれませんので、Windows標準のnslookupができていること、という気持ちは少しばかりあるものの、本件は取り下げます。

なお、IPv6のリンク・ローカル・スコープだけのアドレスに名前を割り当てる是非についても本論ではありません。
ひとつのPCが同じあるいは別のネットワークに接続されて、それぞれでリンク・ローカル・スコープのアドレスを持つことは理解しています。
余談になりますが、現実には、お客様からセキュリティ・ポリシーが設定されたPCが貸与されて、ネットワークの設定でユニーク・ローカルのアドレスfd00/8が設定できない場合で、IPv6通信をしようとするとリンク・ローカルのアドレスを使わざるを得ないという現実もあり、如何ともし難い状況があります。
（予めインストールされているプログラムしか実行できず、Windowsのコマンド・プロンプト画面すら実行できない、というPCがあります。）
Windows標準のものやMS-Teamsなどは問題なく使用できるので、マイクロソフト以外のものが動かないのは仕方ありません。
いずれにせよ、ホスト名の名前解決できなければ、IPv6のアドレスを指定すればよいので、それが対処方法になります。

**Comment by sayurin** [comment]
> Windows標準のnslookup、Linuxのnslookupやプログラムによるgetaddrinfoは、DNSの設定どおりに名前解決する。

こちらは、TCP/IP（UDP/IP）を使用しDNSリクエストを投げ、返された結果ですので、得られる情報は接続先のDNSサーバーに依存します。対して

> Windowsのgetaddrinfoは、IPv6のリンク・ローカル・スコープだけのアドレスの場合、アドレス・ファミリーがAF_UNSPECだと名前解決でIPv6のアドレスを返さない。

こちらは、OS内部のリゾルバライブラリの挙動となります。どう違うかというとわかりやすいのが/etc/hostsなどDNS以外の名前解決手段も含まれる点です。

---

> 何か他にも条件がありそう（IPv6で到達不可能という条件がつきそう）ですが、ホスト名の名前解決がグローバル・スコープのIPv6のアドレスを持つ場合（IPv4とIPv6の両方を持っていても）、そのホスト名に対して名前解決できない。

はい、何らかの条件があり、DNSサーバーとしてはIPv6アドレスも返しているにもかかわらず、リゾルバライブラリでは不採用となりIPv6アドレスが削られているように見受けられます。この条件が気になるところですが、当方でもわかりませんでした。

例えば、 [`AI_ADDRCONFIG` というフラグ](https://docs.microsoft.com/en-us/windows/win32/api/ws2tcpip/nf-ws2tcpip-getaddrinfo)があります。

> If the **AI_ADDRCONFIG** bit is set, **getaddrinfo** will resolve only if a global address is configured. If **AI_ADDRCONFIG** flag is specified, IPv4 addresses shall be returned only if an IPv4 address is configured on the local system, and IPv6 addresses shall be returned only if an IPv6 address is configured on the local system. The IPv4 or IPv6 loopback address is not considered a valid global address.
>
> The **AI_ADDRCONFIG** flag is defined on the Windows SDK for Windows Vista and later. The **AI_ADDRCONFIG** flag is supported on Windows Vista and later.

現在このフラグは指定していませんが、このように適切なIPv6アドレスを持たない場合に検索結果から除外される処理がどこかに含まれているのかもしれません。
