### ISSUE TITLE
WindowsFTPサーバーで日付が正しく表示されない

### ISSUE THREAD

**Issue by beckorz** [ffftp/ffftp#289]
FFFTPのメンテナンスいつもありがとうございます。beckorz と申します。

件名の件ですが、Windowsサーバー上のFTPサーバーにて、フォルダ・ファイル類の日付の表示が正しく表示されない事があるようです。
Windows Server 2016で確認しましたが、別環境のWindows Server 2003でも確認されたので、Windows系のFTPサーバーで起きるようで、他のLinux系のFTPサーバー(FTPサーバーバージョン不明)では不具合事象が確認できませんでした。

### その他
・FFFTP v4.1の時は問題なく、FFFTP v5.1の最新へバージョンアップして利用した際に、不具合事象に気付いた。
・Windows系のIISのFTPサーバーで再現(WinServer2003,2012,2016で確認)
・日付が、10日未満の1～9の日の際に更新日がおかしくなる

![date_format](https://user-images.githubusercontent.com/790009/123553972-ede38f80-d7b8-11eb-916c-57cb62575273.png)

何か、他に確認する必要があれば、確認致しますので、よろしくお願い致します。

**Comment by sayurin** [comment]
「ファイル一覧をビューアで表示」の内容を確認させていただけますでしょうか。

----

まずFTPというプロトコルはファイル一覧を人間が目で見て判断する仕様です。そのため各種FTPクライアントは人間の目を模倣して解釈しています。ffftpでは歴史的に `yy/mm/dd` と `mm/dd/yy` の両方の形式に遭遇しています。

https://github.com/ffftp/ffftp/blob/8ebc7b6f6c1cb952104e5f5ae7cae6357a1cd8df/filelist.txt#L261-L266

https://github.com/ffftp/ffftp/blob/8ebc7b6f6c1cb952104e5f5ae7cae6357a1cd8df/filelist.txt#L274-L279

そのため、FTPサーバーから `01-02-03` が返された場合に `2001年2月3日` でもあり、`2003年1月2日` でもあり得ます。例にあるようにオーバーフローして101年としたり、４桁で2001年とされていれば確実に判別できるのですが…。

----

その上で、従来は

https://github.com/ffftp/ffftp/blob/ba3c51b2703af0d1380df1c823e67652cab998ec/filelist.cpp#L2918-L2942

`xx/yy/zz` のうち、`xx`が1～12であれば `mm/dd/yy` を優先する処理になっていましたが、v4.8でファイル解析処理をリファクタリングした際

https://github.com/ffftp/ffftp/blob/8ebc7b6f6c1cb952104e5f5ae7cae6357a1cd8df/filelist.h#L51-L58

`yy/mm/dd` を満たしていればこちらを優先するように変えてしまいました。
これについては `mm/dd/yy` を優先するように修正しようと思います。

----

本質的には前後の行での判定結果も踏まえて総合的に判定すべきですが、ffftpでは歴史的にほとんど逐次処理となっています。これを改善するのは大掛かりでちょっと厳しいです。

**Comment by beckorz** [comment]
返信ありがとうございます。

「ファイル一覧をビューアで表示」の内容は以下になっておりました。

```
06-27-21  10:57AM       <DIR>          inetpub
07-16-16  10:23PM       <DIR>          PerfLogs
11-08-17  07:26PM       <DIR>          Program Files
07-16-16  10:23PM       <DIR>          Program Files (x86)
11-08-17  06:48PM       <DIR>          Users
06-27-21  10:57AM       <DIR>          Windows
```

動作仕様について詳細に説明ありがとうございます。
FTPでの日付の取り扱いは、プロトコル上曖昧になっていて受け取る側で対応する物なんですね・・・
filelist.txt を見ると、FTPサーバーの実装違いの種類の数が多くて大変さが分かりました・・・

お手数ですが、優先順位の変更が対応出来ればと思います。
