### ISSUE TITLE
シンボリックリンクのディレクトリに移動できない

### ISSUE THREAD

**Issue by kat-no** [ffftp/ffftp#295]
はじめまして。
不具合(?)の報告をさせていただきます。

ホスト上でディレクトリにシンボリックリンクが設定されている場合
Ver 4.8 以降でシンボリックリンクに移動しようとすると
550 Failed to change directory.
となります。

Ver 4.8 からホスト側の表示が
　bar -> foo  2021/01/01 `<`DIR`>`
　foo　　　2021/01/01 `<`DIR`>`
と変わったため、bar をダブルクリックすると
　>CWD bar -> foo
が送信され
　550 Failed to change directory.
となっていると推測します。

Ver 4.7 まではホスト側の表示が
　bar　　　2021/01/01 `<`DIR`>`
　foo　　　2021/01/01 `<`DIR`>`
であったため、問題なかったと思われます。

ご確認の程、よろしくお願い致します。

**Comment by sayurin** [comment]
正しく処理できていなかったので修正します。
