### ISSUE TITLE
シフトＪＩＳコードの文字でＥＵＣに変換する際に間違っているものがある

### ISSUE THREAD

**Issue by YasuoKITAJIMA** [ffftp/ffftp#301]
Windows からシフトＪＩＳコードの２バイト文字「Ａ」～「Ｚ」（大文字の全角アルファベット）をテキスト・モードでＥＵＣで設定されている LINUX に転送すると、「A」～「Z」（大文字の半角アルファベット）に変換されてしまう。例えば以下の通り。
```
ABC
ＡＢＣ
abc
ａｂｃ
123
１２３
+-*/
＋－＊／
あいうえお
アイウエオ
```
   ↓
```
ABC
ABC
abc
ａｂｃ
123
１２３
+-*/
＋－＊／
あいうえお
アイウエオ
```

**Comment by sayurin** [comment]
全角半角変換による誤動作でした。全角半角変換では、

 - `LR"([\uFF61-\uFF9F]+)"` という正規表現を使用して、該当する半角カタカナを抽出し、
 - Unicode正規化を使用して、半角カタカナを全角カタカナへ変換（正規化）し

ています。

v4.4で標準テンプレートライブラリの`std::regex`からBoost.Regex `boost::regex` へ変更しました。その際、[Standards Conformance](https://www.boost.org/doc/libs/1_76_0/libs/regex/doc/html/boost_regex/background/standards.html)で

> The escape sequence \u matches any upper case character (the same as [[:upper:]]) rather than a Unicode escape sequence; use \x{DDDD} for Unicode escape sequences.

と説明されているように非互換がありました。これにより、上記正規表現の `\u` がUnicode文字ではなく大文字にマッチするようになっていました。
またUnicode正規化では半角カタカナは全角カタカナへ変換されますが、それ以外の文字もそれぞれ正規化されます。

これにより`ＡＢＣ`を含む全角大文字アルファベットが変換の対象となり、Unicode正規化により全角大文字アルファベットは半角大文字アルファベットに正規化されていました。
