### ISSUE TITLE
フォルダの同時移動で、同時に移動しない場合がある

### ISSUE THREAD

**Issue by YasuoKITAJIMA** [ffftp/ffftp#313]
バージョン 5.3 で、フォルダの同時移動を指定してフォルダをクリックした場合に同時に移動しない場合があります。
現在分かっている症状は、以下の通りです。
・ＯＳは Windows10 21H1 です。
・同時移動しない症状が発生するのは、Windows 側（左側）のフォルダをクリックした場合のみです。
・フォルダ名が、半角大文字（例えば「TEST」）の場合です。
・ホスト側（右側）のフォルダをクリックした場合は、正常に動作します。
以上、よろしくお願いします。

**Comment by sayurin** [comment]
報告ありがとうございます。原因を特定しました。

- https://github.com/ffftp/ffftp/pull/281/commits/a1a7f8be6f5a86e5f07c846991c2176469566053 この変更で、フォルダ移動に使用するフォルダ名は呼び出し元の文字列を参照する（ローカルコピーしない）
- https://github.com/ffftp/ffftp/pull/300/commits/05d4ae9bf46b98cebe6a80d63055e41267bf251c この変更で、ファイル一覧で表示しているフォルダ名を直接フォルダ移動に渡す

という組み合わせで問題が発生していました。

1. フォルダの同時移動を行うと、まずローカル側が移動します。これは成功します。
2. その際にフォルダ一覧の表示内容も更新されます。
3. この更新により、フォルダ移動が受け取った文字列も変更されてます。
4. リモート側のフォルダ移動は書き変わってしまった不正文字列のフォルダに移動しようとします。これは失敗します。

フォルダ移動ではローカルコピーを行うようにコードを修正します。
