### ISSUE TITLE
環境設定 ＞ 転送3 ＞ 属性が設定できないエラー

### ISSUE THREAD

**Issue by Matsumoto0014** [ffftp/ffftp#317]
いつもありがとうございます。
FFFTP ver 5.3（64bit版）で以下のような問題を見つけました。

・環境設定 ＞ 転送3  で属性の設定が正常にできません。
・属性のところにファイル名が登録されてしまいます。
▽例
《ファイル名：*.cgi／属性：705》と入力すると
《ファイル名：*.cgi／属性：*.cgi》と登録されます。

確認環境は、Windows10／64bitです。
どうぞよろしくお願いいたします。

![スクショ13](https://user-images.githubusercontent.com/91304277/134618381-b2e1c4ea-d996-469b-8eaa-ffaa574ccb38.png)

**Comment by sayurin** [comment]
すみません、v5.0で取り込まれている https://github.com/ffftp/ffftp/commit/899ffbfe91953579e4f0467213120040229991b4 この変更で、変数名が誤っていました。修正します。
