### ISSUE TITLE
ミラーリング時、同じタイムスタンプのファイルが対象となってしまう

### ISSUE THREAD

**Issue by Matsumoto0014** [ffftp/ffftp#318]
いつもありがとうございます。FFFTP ver 5.3（64bit版）で以下のような問題を見つけました。

・ミラーリングアップロード時に、同じタイムスタンプのファイルが対象となります。
・同じタイムスタンプのファイルは対象外となるようにしていただきたいです。

確認環境は、Windows10／64bitです。
どうぞよろしくお願いいたします。

![スクショ13](https://user-images.githubusercontent.com/91304277/135425338-4d8ab7aa-491d-4966-907f-86c5181a723a.png)

**Comment by sayurin** [comment]
すみません、v5.3で取り込まれた #300 の影響です。それ以前は画面に表示している文字列を再パースして復元されたタイムスタンプをもって大小比較をしていました。 #300 では、OSから取得したタイムスタンプをそのまま保持するようになりました。

OSでは１秒よりも細かい精度でタイムスタンプが記録されています。そのため、表示上は同じ秒数であってもローカルの方が新しいという振る舞いになってしまうようです。

安直にはローカル側に＋１秒して計算すれば良さそうですが、そもそもftpサーバー側が分精度でしか値を返さない場合などもあり、簡単には解決できない事情があります。
比較の際に、ローカル側のタイムスタンプを「リモート側が返した時刻精度」まで丸めてから比較するのが妥当かなぁ…？ となると、「リモート側が返した時刻精度」を検出する機能が必要になりますねぇ…。

**Comment by Matsumoto0014** [comment]
ご確認いただきましてありがとうございます！
難しい問題なのですね・・・

「ミラーリングアップロード」と
通常アップロードの「新しければ上書き」は、よく使っており、解決すると嬉しいですが、
解決するまでは、更新日順でローカルファイルをソートして
ファイル個々に選択してアップロードする事にいたします。

また、添付スクショの赤枠部分の「説明文」につきましては
旧仕様の名残かと思いますので、外していただいても良さそうです。

![スクショ11](https://user-images.githubusercontent.com/91304277/135781851-546968d5-e22a-4310-bd54-fc1f4e5839ba.png)
