### ISSUE TITLE
ファイル一覧の表示に時間がかかる

### ISSUE THREAD

**Issue by riku22** [ffftp/ffftp#327]
FFFTP V5.4に更新したところ、ファイル一覧の表示に2分程度とかなり時間要するようになってしまいました。
ファイル数は20個から40個程度と、そこまで多くないと思います。
FFFTP V5.3では問題ありませんでした。
ちなみに、相手方のサーバーはレンタルサーバーで、ログを見る限りPureFTPで動いているようです。
また、ProFTPで動いていると思われる別のサーバーも試してみましたが、こちらは問題ないようでした。
ログや接続先等の情報が必要でしょうか。
環境は、Windows10 21H1 64ビット、FFFTP V5.4 64ビット版です。
よろしくお願いいたします。

**Comment by sayurin** [comment]
ftps接続で暗号化されているのですね。念のため確認ですが、

```
>AUTH TLS
234 AUTH TLS OK.
   <=== ここ
>PBSZ 0
200 PBSZ=0
```

このタイミングで同様の待ち時間は発生していませんよね？ ここでも発生している場合、TLS / 証明書関連となりますが、そうでない場合は別要因となります。

----

以下は、発生していない前提です。

ftps接続を行うとWindows Firewallが通信内容を誤解し、ブロックされてしまうトラブルが報告されています。Windows Firewallの設定変更を行い、問題を回避することができます。管理者コマンドプロンプトで

```
netsh advfirewall set global StatefulFTP disable
```

と実行します。この機能はffftpのメニュー 「WindowsファイアウォールのステートフルFTPフィルタの設定」からでも実行可能です。実行方法はどちらでも構いませんので、試していただけないでしょうか。

**Comment by riku22** [comment]
`234 AUTH TLS OK.`

上記部分での待ち時間はありません。
ただ、暗号化なしでの接続を試したところ、すぐにファイル一覧が表示されたので、もしかしたらこのあたりが問題なのでしょうか。
また、Windows Firewallの設定変更は、特に効果はないようでした。

**Comment by sayurin** [comment]
tt4g さんありがとうございます。その可能性もあるかもしれませんが、ffftp v5.3までは遅くなかったとのことなので、`/dev/random` が原因ではないかもしれません。

riku22 さん、 statefulftpは原因ではなかったとのこと、了解です。設定を元の状態に戻しておいていただけますでしょうか。
暗号化の有無で違いが出ることから、暗号化に原因があることは確実そうです。ただし、`234 AUTH TLS OK.` の後で開始される暗号化には遅延が見られないとのことがよくわからないです。（両方で発生するのであれば、例えば証明書の失効確認で接続エラーが発生する等もあり得るのですがそうではなさそうで。）また、セキュリティ上問題があるなら遅延ではなく何らかエラーになるべきであり、そうではないこともよくわからないです。

レンタルサーバーとのことですので、提供されているサービス会社・プラン名等を教えていただけないでしょうか。無料体験サービスがあれば、私の方で申し込んで確認してみたいのですが。

**Comment by sayurin** [comment]
手元の環境でpure-ftpdを構築してみたところ、再現したため、調査を行うことができ、原因を特定できました。

一般的なTCP/IPでは、データを送信終了した際に`shutdown()`によりデータ送信終了を伝えます。しかし、pure-ftpdでは`shutdown()`せずに`close()`していました。このため、ffftpではファイル一覧の終端を検出できずにタイムアウト待ちしていました。
ただし、pure-ftpdは`shutdown()`はしていませんがTLSレベルで`tls_close_session()`によりセッション終了していました。ffftp v5.3まではセッション終了を検出できていましたが、ffftp v5.4への更新の際、セッション終了を正しくハンドリングできていませんでした。

[pure-ftpdの終了処理](https://github.com/jedisct1/pure-ftpd/blob/1.0.49/src/ftpd.c#L2367-L2377)

```
void closedata(void)
{
    volatile int tmp_xferfd = xferfd;   /* do not simplify this... */

#ifdef WITH_TLS
    tls_close_session(&tls_data_cnx);     <------- ffftp v5.3まではこれを検出
    tls_data_cnx = NULL;
#endif
    xferfd = -1;           /* ...it avoids a race */

    <--------- 本当はこの辺りでshutdown()を呼び出してほしい

    (void) close(tmp_xferfd);
}
```
