### ISSUE TITLE
設定したサウンドが再生されない

### ISSUE THREAD

**Issue by riku22** [ffftp/ffftp#328]
コントロールパネルの「サウンド」の「サウンド」タブにあるサウンドの設定で、接続時やエラー時などにサウンドが再生されるように設定しました。
しかし、V5.3までは正常に再生されていましたが、V5.4に更新したところ、再生されなくなってしまったようです。
なおコントロールパネルの画面にある「テスト」ボタンでは正常に再生されています。
環境は、Windows10 21H1 64ビット、FFFTP V5.4 64ビット版です。

**Comment by sayurin** [comment]
直接の原因は無駄な https://github.com/ffftp/ffftp/issues/337 と同じく無駄なmutexを削除したことでした。これにより、転送完了のサウンド再生が連発されていました。OSとしては再生のし過ぎということで再生そのものを放棄されてしまい、結果として再生されないという状態になっていました。（放棄されていなければ音が無限に出続けていました）

しかし、根が深く真の原因は別のところにありました。転送スレッド各々が各々の判断で転送終了を検出しているため、従来でもスレッド個数分のサウンド再生が行われていました。
スレッド間での転送状態を踏まえて転送完了を検出することで、１回のみの再生となり、同時に前者の問題も解消できる見込みです。
