### ISSUE TITLE
ＳＪＩＳ（Windows） のテキスト・ファイルをアスキー・モードでＥＵＣ（LINUX）に転送すると改行が挿入される場合がある

### ISSUE THREAD

**Issue by YasuoKITAJIMA** [ffftp/ffftp#329]
[tmp.txt](https://github.com/ffftp/ffftp/files/7343493/tmp.txt)
　添付したファイル（Windows マシンのＳＪＩＳコード）をアスキー・モードでＥＵＣマシン（LINUX）に転送すると、23988 行目 と 23989 行目の間に改行コードが挿入されます。
　添付ファイルの 2 行目を削除すると、この現象は発生しません。
　添付ファイルの 2 行目と 3 行目の間に文字列を追加すると、改行が挿入される位置が変わります。
　Windows のコマンド・プロンプトから ftp コマンドでアスキー転送した場合には、この現象は発生しません。（漢字コードは変換されないままです。）
　ffftp でホストの漢字コードをＳＪＩＳに設定しても、改行は同じ位置に挿入されます。（漢字コードは変換されないままです。）
　以上、よろしくお願いします。

**Comment by sayurin** [comment]
すみません、わかってはいたのですが、あえて作り込んでいました。

ffftpはアップロードの際、一定のブロックサイズに分割し、ブロックごとに

1. 漢字コード変換
2. 改行コード変換

を行ってから送信します。

漢字コード変換は、マルチバイト文字がブロック境界に挟まれると正しく漢字を認識できないため絶対に文字化けします。
改行コード変換は、従来ブロック境界を考慮した変換がされていました。しかし、漢字コード変換でのブロック境界を無視した変換、それによる文字化けが受け入れられているのであれば、改行コード変換についても同様に文字化けしてもいいのではないかと考え、 [v3.7でのリファクタリング](https://github.com/ffftp/ffftp/commit/43df2f290cf19a5e743961213780be2bb2e73ebc)の際に、ブロック境界を無視した変換に変更しました。

漢字コード変換と改行コード変換の両方を考慮してブロック境界をずらす処理を組み込みます。

**Comment by sayurin** [comment]
本件の発生条件：
 - 漢字コード変換の文字化け： ～ v5.4
 - 改行コードの不正： v3.7 ～ v5.4

v4.9系でも発生するが、対応はひとまず見送る。

**Comment by YasuoKITAJIMA** [comment]
いつもお世話になっております。
バージョン 5.4 で問題が発生する（改行が挿入される）データを、バージョン 5.5 で転送してみました。
1250 行目あたりに挿入されていた改行は、挿入されなくなりました。
ただファイルの末尾（1343 行目あたり）に、他の部分が追加されてしまい、最終的には 2539 行になってしまいました。
以上、添付ファイルでご確認ください。

**Comment by YasuoKITAJIMA** [comment]
添付ファイルです。
[th_comp_sets_auto_d.ZIP](https://github.com/ffftp/ffftp/files/7568249/th_comp_sets_auto_d.ZIP)

**Comment by sayurin** [comment]
ひとまずreopenします。確認後、新たなIssueに分離するかもしれません。

**Comment by sayurin** [comment]
新たに #344 が立てられたのでそちらで対応します。そのためこちらはcloseします。
