### ISSUE TITLE
コマンドラインでミラーリングが動作せず強制終了する

### ISSUE THREAD

**Issue by hiroses2** [ffftp/ffftp#337]
いつもお世話になっています。
先日4.9系からv5.4にアップデートしました。
バッチファイルでミラーリングを起動しているのですが、

start "" "C:\Program Files\ffftp\ffftp.exe" -z password -s "hoge" -m -f -q
とすると、画面が一瞬表示されるものの、強制終了してしまうようです。

ミラーリングのオプションなし
start "" "C:\Program Files\ffftp\ffftp.exe" -z password
だと、画面が表示されます。

とりあえずv4.9系に戻すと大丈夫なので、使っています。
取り急ぎご報告いたします。

環境
Windows 10 Pro for Workstations 64bit版　
バージョン 20H2
OSビルド 19042.1288

**Comment by sayurin** [comment]
すみません、こういうことは起こるだろうなという予感はありました…。

従来、ファイルの送受信処理を行うループにはmutexが用意されていました。しかし実際にはmutexが解放されることはなく、１ファイル操作毎に指定された200msでタイムアウトするだけの存在となっていました。で、ミラーリング起動の際、１回目の200msのタイムアウト待ちの間に初期化処理が完了できればミラーリングが開始されるという危うい実装になっていました。
[v5.4のリファクタリング](https://github.com/ffftp/ffftp/commit/a4e449f8d6138fb1832691a766bd175e3f6138f4)の際、無駄なmutexを削除しましたが、この副作用で初期化処理が完了するよりも先に送受信処理が終了してしまうようになりました。

本質的な対応として、初期化完了のフラグを導入します。

**Comment by hiroses2** [comment]
ご回答ありがとうございます。
なるほど、状況承知いたしました。早速のご対応感謝いたします。
