### ISSUE TITLE
ファイルをアップロードすると、末尾におかしな文字が追加される

### ISSUE THREAD

**Issue by kouna426** [ffftp/ffftp#344]
FFFTP Ver.5.5 64bit版でファイルをアップロードすると、末尾におかしな文字（TeraPadで開くと「Null文字」と警告されました）が大量に追加され、ファイルサイズも肥大してしまいます。

元データ：[aaa.txt](https://github.com/ffftp/ffftp/files/7574067/aaa.txt)
アップロード後のデータ：[aaa-bug.txt](https://github.com/ffftp/ffftp/files/7574068/aaa-bug.txt)

上記ファイルは拡張子が「txt」ですが、「htm」や「html」の拡張子でも同じ問題が発生しました。
FFFTP ver.5.4で同ファイルのアップロードを試したところ、この問題は発生しませんでした。
OSはWindows 10 Pro バージョン21H1です。

GitHubを使うのは初めてなので、報告に拙いところがありましたら申し訳ありません。
ご確認いただけますと幸いです。よろしくお願いいたします。

**Comment by sayurin** [comment]
報告ありがとうございます。他でも指摘があるため、たぶんバグだと思います。調査していますが、ぱっと見ではまだ原因が見つかっていないです。

**Comment by kouna426** [comment]
v5.5.1に更新したところ、問題が発生しなくなりました。
迅速に対応していただきありがとうございました！

**Comment by YasuoKITAJIMA** [comment]
v5.5.1 で問題が解決しました。
以上、よろしくお願いします。
