### ISSUE TITLE
接続直後に切断されてしまう

### ISSUE THREAD

**Issue by sayurin** [ffftp/ffftp#352]
Twitterで報告を受けました。5.1 / 5.3までは動作していたが、5.4 / 5.5.1では動作しなくなったとのこと。

> 「処理内容をビューアで表示」すると、「接続しました.」「接続できません.」が連続して表示されて終わっています。

> TCP接続確立直後に、相手からのFTPの応答パケットが出る前にこちらから接続を切りに行きますので、何かを応答コードと間違ってエラー処理をしている可能性が高いように思います。

このため、 [5.3 ～ 5.4 の修正](https://github.com/ffftp/ffftp/compare/v5.3...v5.4#diff-6bb04ca690d70bd5421b5d5c0c5912cbd944b394d76660167795433a3bfbc892)でエンバグした可能性が高い。

**Comment by sayurin** [comment]
> 「接続しました.」「接続できません.」が連続して表示され

となるのは、
https://github.com/ffftp/ffftp/blob/ef69f542e5256ac8a7a683f86dcab015d36d1299/connect.cpp#L1169-L1191
この部分で`connectsock()`内で「接続しました.」と表示し成功したのち`Sts`が`FTP_COMPLETE`以外の値になり`if`文が`else`に流れて「接続できません.」と表示されるパターン。
そうなるのは
- `CryptMode`が`CRYPT_FTPIS`で`ContSock->AttachSSL()`が失敗した時
- `ContSock->ReadReply()`が`FTP_COMPLETE`以外を返した時
のどちらか。ここで、

> 「FTPS (Explicit)で接続」のみをonにしても同様に、v5.3では正常に動き、v5.4以降では問題が発生しています。

とのことから、`CryptMode`が`CRYPT_FTPIS`ではなく、後者のみが該当しそう。

> socket.cppのReadReplyを疑ってるとこ、という情報は蛇足かしら。400番台のコードが返ってきていると解釈されているところまでは追えました。

とのコメントとも一致する。

**Comment by sayurin** [comment]
> connect.cpp内のDoConnectCrypt()内でconnectsock()を呼んだ直後にSleep(40)を入れてやると先へ進むことが出来ました。

とのことで、接続直後に `SocketContext::ReadReply()` を呼び出すと読み出しに失敗する何らかの条件が存在する模様。

**Comment by eman1972** [comment]
Twitterにて報告させていただいた者です。
プログラムの流れを把握できておりませんので的外れな情報かもしれませんが、参考までにこちらでこれまでに調べた結果をお伝えしたいと思います。
こちらの環境での動作は次のようになっています。
connectsock()を呼んだ後、if(CryptMode == CRYPT_FTPIS)には該当せず、elseの方に入ります。
そこにwhileループがありますが、ReadReply()が一度だけ実行されて抜けてきます。
おそらくそこは受信待ちをする部分だと推測していますが、受信を待っておりません。

ReadReply()内では size(readPlain) の値が0であり、
関数内関数のWait()内の二つのif文のどちらにも該当せず return{} で抜けてきます。
value_or() によってステータス 429 が渡されて出てくるようです。

**Comment by sayurin** [comment]
> ReadReply()内では size(readPlain) の値が0であり、
> 関数内関数のWait()内の二つのif文のどちらにも該当せず return{} で抜けてきます。

`Wait()`関数はコールバック関数が`false`を返す限り待ち続けるものです。

https://github.com/ffftp/ffftp/blob/ef69f542e5256ac8a7a683f86dcab015d36d1299/socket.cpp#L568-L581

二つのif文はこの部分ですが、580行目の`return {}` は`false`と判定され、追加データを受信できるまで待つことを指示しています。
その意味では、こちらの`Wait()`関数ですが

https://github.com/ffftp/ffftp/blob/ef69f542e5256ac8a7a683f86dcab015d36d1299/socket.cpp#L217-L238

`test()`コールバックが`false`を返した場合は`for(;;)`ループを継続します。`for(;;)`ループを脱出する条件は

- 222行目、通信に何らかのエラーが発生した場合
- 225行目、タイムアウトした場合
- 229行目、UIから停止された場合

となります。UIから停止はされていないので、まずは「設定」-「転送2」-「ネットワークタイムアウト時間」が極端に小さな値になっていないか確認をお願いしたいです。

並行して、通信にエラーが発生した（バグによりエラーと誤判定した）可能性を確認します。

**Comment by eman1972** [comment]
タイムアウト時間が0になっておりました。
1にしただけでv5.4、v5.5.1ともに直りました。

この設定の存在を忘れていて申し訳ない気分です。
長々と問題にお付き合いいただきましてありがとうございます。

**Comment by sayurin** [comment]
いえいえ、原因が判明して何よりです。プログラム側としてもタイムアウトで切断したのであればその旨を出力するべきですので、改善します。（メッセージを読めばタイムアウトを見直す動機づけになりますし）

**Comment by sayurin** [comment]
改めて確認したところやはりバグでした。

> ネットワークタイムアウト時間
> （0～300秒; 0=タイムアウトなし）

ですので、説明に従うなら `0` はタイムアウトすべきではなく、バグです。修正します。
