### ISSUE TITLE
ダークモード化

### ISSUE THREAD

**Issue by tablacus** [ffftp/ffftp#356]
私はアプリをダークモード化するDllを作成しています。

https://github.com/tablacus/TablacusDark

このdllを使用すると以下の様にFFFTPをWindowsのダークモードに対応できました。

![image](https://user-images.githubusercontent.com/5156977/145404877-41f4a767-bef1-45ec-a7e4-22434b6011b0.png)

![image](https://user-images.githubusercontent.com/5156977/145404791-94ac6d55-d66f-4677-b4df-238c3de3f0a5.png)

![image](https://user-images.githubusercontent.com/5156977/145404970-b3b512ac-b682-4da2-9d11-015a73022f21.png)

![image](https://user-images.githubusercontent.com/5156977/145405157-2a8f33e7-1b98-429f-8ed6-d5e9a9f36651.png)

![image](https://user-images.githubusercontent.com/5156977/145405269-407c7aba-1449-41db-972a-8649b75fa084.png)

![image](https://user-images.githubusercontent.com/5156977/145406976-f197fe4a-8dfc-4858-8c9c-8407ac1348a3.png)

![image](https://user-images.githubusercontent.com/5156977/145407026-8b361213-7ded-4740-b2fa-dbef0d2fe107.png)

このDllを読み込む機能を FFFTP に追加してプルリクしても良いでしょうか？
読み込みは以下の様な感じになります。

```C++
typedef void (__stdcall* LPFNEntryPointW)(HWND hwnd, HINSTANCE hinst, LPWSTR lpszCmdLine, int nCmdShow);

	WCHAR pszPath[MAX_PATH];
	::GetModuleFileName(NULL, pszPath, MAX_PATH);
	::PathRemoveFileSpec(pszPath);
#ifdef _WIN64
	::PathAppend(pszPath, L"tablacusdark64.dll");
#else
	::PathAppend(pszPath, L"tablacusdark32.dll");
#endif
	HMODULE hDark = LoadLibrary(pszPath);
	if (hDark) {
		LPFNEntryPointW _SetDarkMode = NULL;
		LPFNEntryPointW _SetAppMode = NULL;
		LPFNEntryPointW _FixWindow = NULL;
		*(FARPROC*)&_SetDarkMode = GetProcAddress(hDark, "SetDarkMode");
		*(FARPROC*)&_SetAppMode = GetProcAddress(hDark, "SetAppMode");
		*(FARPROC*)&_FixWindow = GetProcAddress(hDark, "FixWindow");
		_SetDarkMode(hWndFtp, NULL, NULL, -1);
		_SetAppMode(NULL, NULL, NULL, -1);
		_FixWindow(hWndFtp, NULL, NULL, 1);
	}
```

**Comment by sayurin** [comment]
試みとしては面白いですが、どうせフックするなら対象アプリのコード修正なしで、プロセス侵入からフックで実現してはどうでしょうか？
私自身は `SetWindowsHookEx` を使ってプロセス侵入するプログラムを書いたりします。

アプリケーション側で対応するなら、OSテーマへの追従かなと思います。今はOS側でダークモードを提供していますので。

**Comment by tablacus** [comment]
了解です。上記のdllはOSテーマへの追従します。

**Comment by sayurin** [comment]
ちなみに、プロセス侵入・フックをする際、実行ファイルのバージョンが3.0以上であるかを確認するようにしてください。

https://github.com/ffftp/ffftp/blob/archive/2.00/src/protectprocess.c

このように2.00以下にはフック対策コードが組み込まれています（3.0でこの機能は外しました）。
