### ISSUE TITLE
ミラーリングアップロードの「一覧から削除」が正常に動作しない

### ISSUE THREAD

**Issue by iooiau** [ffftp/ffftp#361]
ミラーリングアップロードを行う場合に「処理内容表示」で一覧を表示させ、そこから項目を選択して「一覧から削除」で削除しようとしても正常に動作しません。
先頭の項目を選択すれば削除されますが、他の項目を選択しても削除されません。
Ver 5.6 で確認しました。

**Comment by iooiau** [comment]
https://github.com/ffftp/ffftp/blob/4b0fdbc5dba72c0d6f815f40b870b98e35fd9ad9/ftpproc.cpp#L310-L311

ここの indexes が list の誤りと思います。

**Comment by sayurin** [comment]
具体的な指摘ありがとうございます。確認します。
