### ISSUE TITLE
ファイルではなくディレクトリが作成される

### ISSUE THREAD

**Issue by yenpower** [ffftp/ffftp#369]
ffftp v5.6において、
「ホスト名に同じ名前のファイルがあります」という状態のとき、
名前を変更して「上書き」ラジオボタンを選択し、「OK」ボタンを押下すると、
当該ファイルが違う名前でアップロードされず（アップロード自体、未解決）、
【変更した名前のディレクトリ（フォルダー）が作成】されてしまいます。

**確認環境情報**
・Windows 10 Pro（21H1）
・ffftp v5.6（x64）

**FTPサーバー環境情報**
・Windows Server 2019 Standard Version 1809
・Internet Information Services(IIS）Manager Version 10.0.17763.1

**操作概要**

1. リモート側にすでに存在しているファイル名（TEST.txt）と同じファイル名の、ローカル側のファイル（TEST.txt）を選択し、アップロード。
2. アップロードの確認画面にて、名前を変更（TEST.txt → TEST2.txt）して「上書き」
3. アップロードが完了しないため「このファイルを中止」
4. リモート側にてファイル一覧が白紙になる。最新の情報に更新（F5）も効かない。
5. 再接続
6. リモート側に「TEST2.txt」という名のディレクトリが作成されている。

1.同名ファイルをアップロード
![1](https://user-images.githubusercontent.com/23088523/163302570-eae9d16d-c1e0-4c90-9d14-db9ec6061c27.png)

2.ファイル名を変更
![2](https://user-images.githubusercontent.com/23088523/163302579-2ac2bac4-22b9-4c83-b1e0-f0b6393e0e38.png)

3.アップロード（中止）
![3](https://user-images.githubusercontent.com/23088523/163323820-ce52d8db-ea0d-4948-ae98-caca0d980bf5.png)

4.リモート側、白紙
![4](https://user-images.githubusercontent.com/23088523/163323760-50e1c786-d494-4854-813f-e17bc91cb670.png)

5.（再接続）

6.ディレクトリが作成されている
![6](https://user-images.githubusercontent.com/23088523/163323727-84b34b89-09bc-4b0b-a643-d843868dde04.png)

**処理内容**
```
----------------------------
通信は暗号化されていません.
第三者にパスワードおよび内容を傍受される可能性があります.
ホスト XX.XXX.X.252 (XX.XXX.X.252:21) に接続しています.
接続しました.
220 Microsoft FTP Service
>USER ZZZZZZZZ
331 Password required
>PASS [xxxxxx]
230 User logged in.
>FEAT
211-Extended features supported:
 LANG EN*
 UTF8
 AUTH TLS;TLS-C;SSL;TLS-P;
 PBSZ
 PROT C;P;
 CCC
 HOST
 SIZE
 MDTM
 REST STREAM
211 END
>>CD D:\FFFTP_TEST
>CWD /99_test
250 CWD command successful.
>XPWD
257 "/99_test" is current directory.
>TYPE A
200 Type set to A.
>PASV
227 Entering Passive Mode (XX,XXX,X,252,249,245).
ダウンロードのためにホスト XX.XXX.X.252 (XX.XXX.X.252:63989) に接続しています.
接続しました.
>NLST -al
125 Data connection already open; Transfer starting.
226 Transfer complete.
ファイル一覧の取得は正常終了しました. (49 Bytes)
>MKD /99_test/TEST2.txt
257 "/99_test/TEST2.txt" directory created.
>TYPE I
200 Type set to I.
>PASV
227 Entering Passive Mode (XX,XXX,X,252,249,252).
アップロードのためにホスト XX.XXX.X.252 (XX.XXX.X.252:63996) に接続しています.
接続しました.
>STOR /99_test/TEST2.txt
コマンドが受け付けられません.
アップロードを中止しました.
>TYPE A
ファイル一覧の取得を中止しました.
ファイル一覧の取得に失敗しました.
>QUIT
切断しました



（再接続）



----------------------------
通信は暗号化されていません.
第三者にパスワードおよび内容を傍受される可能性があります.
ホスト XX.XXX.X.252 (XX.XXX.X.252:21) に接続しています.
接続しました.
220 Microsoft FTP Service
>USER ZZZZZZZZ
331 Password required
>PASS [xxxxxx]
230 User logged in.
>FEAT
211-Extended features supported:
 LANG EN*
 UTF8
 AUTH TLS;TLS-C;SSL;TLS-P;
 PBSZ
 PROT C;P;
 CCC
 HOST
 SIZE
 MDTM
 REST STREAM
211 END
>>CD D:\FFFTP_TEST
>CWD /99_test
250 CWD command successful.
>XPWD
257 "/99_test" is current directory.
>TYPE A
200 Type set to A.
>PASV
227 Entering Passive Mode (XX,XXX,X,252,250,11).
ダウンロードのためにホスト XX.XXX.X.252 (XX.XXX.X.252:64011) に接続しています.
接続しました.
>NLST -al
125 Data connection already open; Transfer starting.
226 Transfer complete.
ファイル一覧の取得は正常終了しました. (99 Bytes)
```

**Comment by sayurin** [comment]
情報ありがとうございます。こちらは確かにディレクトリを作成しようとしているので、バグだと思います。原因を特定します。
```
>MKD /99_test/TEST2.txt
257 "/99_test/TEST2.txt" directory created.
```

**Comment by sayurin** [comment]
https://github.com/ffftp/ffftp/commit/37ab1a077d73411eb7bd3805c00bc5f96d7f3c5c このコミットでエンバグしたっぽい。
