### ISSUE TITLE
半角スペースのみのファイル名やフォルダ名が正しく表示されない

### ISSUE THREAD

**Issue by Kurukuru-Shisa** [ffftp/ffftp#381]
半角スペースのみのファイル名やフォルダ名がリストの「名前」列に表示されず、代わりに日付が「名前」列に表示される。
この状態では、右クリックメニューの削除や名前変更が動作しない。

![space](https://user-images.githubusercontent.com/109164730/185016708-778debdf-9e53-479d-8b42-09efa28217b7.png)

**Comment by sayurin** [comment]
次の２つの理由から対応しないこととします。

#### ftpは本来、人が目で見て判断するプロトコルです。

サーバーからは`ls`もしくは`DIR`コマンド相当の文字列が送られてきます。ffftpやその他のftpクライアントはそれを解析しているに過ぎません。可変長の空白区切りなため、半角スペースのみのファイルを認識することができません。その後`MLSD`コマンドが規定されましたが、こちらもファイル名の直前は空白区切りであり、やはり半角スペースのみのファイルを認識することができません。 [filelist.txt](https://github.com/ffftp/ffftp/blob/v5.7/filelist.txt) も参考にどうぞ。

#### Windowsのファイル名の命名規則に反しています。

[ファイル、パス、名前空間の名前付け - 命名規則](https://docs.microsoft.com/ja-jp/windows/win32/fileio/naming-a-file#naming-conventions)には

> - ファイル名またはディレクトリ名をスペースまたはピリオドで終了しないでください。 基になるファイル システムではこのような名前がサポートされる場合がありますが、Windows シェルとユーザー インターフェイスではサポートされません。

に違反します。
