### ISSUE TITLE
接続ホストのヒストリ個数

### ISSUE THREAD

**Issue by halt76** [ffftp/ffftp#382]
v4.4 以後、接続ホストのヒストリ個数を 0 にすると起動しなくなります。
以前は切断時に落ちたりしていました。
イベントには 0xc0000409 が記録されています。

**Comment by sayurin** [comment]
OSS化当初からヒストリ個数 0 を想定していないコードになっていました。

https://github.com/ffftp/ffftp/blob/2bf85c03c1e059a2f75dbd48ef73be5961e12414/history.c#L103-L120

ヒストリを追加する前に`CheckHistoryNum(1)`でスペースを１個分空けます。

https://github.com/ffftp/ffftp/blob/2bf85c03c1e059a2f75dbd48ef73be5961e12414/history.c#L147-L180

内部では `FileHist-Space` とやっていてunderflowを引き起こしていました。

----
v4.4 で行った https://github.com/ffftp/ffftp/pull/157 リファクタリング後の現在の実装でも

https://github.com/ffftp/ffftp/blob/f2de70b1c6da6051ee90df35dc5867d107a0ed50/history.cpp#L48-L52

スペースを１個分空ける際にunderflowを引き起こしていました。これが原因で起動できなくなっているようです。
