### ISSUE TITLE
接続直後にすぐ「接続できません」と出ます

### ISSUE THREAD

**Issue by minuet4869** [ffftp/ffftp#385]
https://github.com/ffftp/ffftp/issues/352

こちらと同じようなことが発生いたしました。
上記リンク内に記載のある通りに対処しても改善しません。

**Comment by sayurin** [comment]
「対処」とは具体的には何をしたのでしょうか？

使用バージョンを教えてください。また5.3以前では接続できますでしょうか？ （接続できないなら別件かと）

使用プロトコルを教えてください。 FTP（暗号化なし）or FTPS （Explicit） or FTPS （Implicit）

**Comment by minuet4869** [comment]
対処に関してです。
リンク先のものですとタイムアウト時間の変更をしました。
他にも、
・使用プロトコルの変更（全て試してみました）
・バージョンの変更（5.3で試しました）
上記試しましたが改善しません。

初期段階で使用していたバージョンは5.7です。

**Comment by minuet4869** [comment]
対処に関してです。
リンク先のものですとタイムアウト時間の変更をしました。
他にも、
・使用プロトコルの変更（全て試してみました）
・バージョンの変更（5.3で試しました）
上記試しましたが改善しません。

初期段階で使用していたバージョンは5.7です。

**Comment by minuet4869** [comment]
インストールし直しましたら直りました。
ご迷惑をおかけしました。
