### ISSUE TITLE
No more async regist space エラー

### ISSUE THREAD

**Issue by honeylover** [ffftp/ffftp#62]
お久しぶりです。
ミラーリングダウンロードで大量（と言っても2000弱）をダウンロード中、No more async regist space というエラーが出てOKを押すとFFFTPが終了してしまいます。終了というか消えて無くなる感じ。オプション設定した後だったら保存できてるかどうかは不明。

![Image of FFFTP error](https://i.imgur.com/gkMI5gb.png)

ミラーリング自体は関係ないかもしれません。メモリは12GB積んであって、半分以上余裕がある状態なのでRAM不足とは考えにくいです。バッファ容量が足りないとか、よく分かりませんが、プログラムの中で制限値に達してしまっているように思います。
3.3と3.5で起きました。

**Comment by honeylover** [comment]
おそらくこのエラーで落ちたことが原因と思いますが、あるファイルがゼロバイトになっていてタイムスタンプがその時点のものになっているのを発見しました。

というのも、ミラーリングアップロードのリストアップしてみたら、アップロードしたはずのファイルがリストアップされたので不安に思い、サーバーの方を確認してみたら上記のような現象になっていました。本来はタイムスタンプを維持するように設定しているのですが、転送完了せずに落ちたためにタイムスタンプの変更も当然されなかったのでしょう。

危うく、ゼロバイトのファイルでローカルファイルを上書きしてしまうところでした。
転送中のフリーズは怖いですね。データベースの更新失敗時みたいにロールバックとかもできませんしね。。。

転送数が影響していることはあり得ますか？あるなら3とか2に減らしてみようと思いますが…。

**Comment by sayurin** [comment]
このエラーの回避策としてはやはり転送数を減らすことですね。転送処理は抜本的に見直す予定はありますが、まだ手を付けられていません。

**Comment by honeylover** [comment]
了解です。とりあえず転送数を減らして対処することにします。ありがとうございます。

**Comment by honeylover** [comment]
今日また出ました。接続数2でも出てしまいました。
何らかのエラーでFFFTPが止まってしまって、動作を一旦キャンセルし、FFFTPの再起動をせずに多くのダウンロードをしようとするとこのエラーが出るような気がします。確証はありませんが。。。
その「何らかのエラー」については別に投稿します。

**Comment by sayurin** [comment]
本Issueで言及されているエラーは`AsyncTable`関連ですが、#310 で導入した`SocketContext`に統合され、async regist ？という行為そのものが不要な構造となりました。
