### ISSUE TITLE
SOCKS5 Proxy経由で接続できない

### ISSUE THREAD

**Issue by s-im** [ffftp/ffftp#93]
勤務先はSOCKS5（認証無し）を経由しないと外部サーバーに接続できない環境です。この環境で使わせて頂いているのですが、最近外部に繋げられなくなっておりました。v3.4までバージョンダウンすると繋がるようになります。
一方で、curl.exe（windows10-1803以降の\windows\system32に格納されています。ソースからビルドした物でも可能）を使って Adobe Acrobat Reader DC が置かれているディレクトリを見るために
curl --socks5 xxx.xxx.xxx.xxx:pppp ftp://ftp.adobe.com/pub/adobe/reader/win/AcrobatDC/
を実行すると、内容を確認出来ます。（Proxyサーバーは伏させて頂いています）
自宅で「socks proxy list」で検索して見つかった中で（curl.exeで確認した）実際に繋がるサーバーを経由しても同様でした。繋がらないときの症状は「受信中止」ボタンしか押せない状態です（添付ファイル参照）。そしてしばらくするとタイムアウトで戻ってきます。

v3.5の更新内容に「DNS名前解決、サーバー接続関連のソースコードをリファクタリングしました。」とありますが、この作業で変数名が被ってしまったとかありませんでしょうか。ご確認頂けましたら幸いです。

![ffftp-socks5](https://user-images.githubusercontent.com/50191156/57057117-bf092600-6ce1-11e9-9499-40d1f96eae55.png)

**Comment by sayurin** [comment]
報告ありがとうございます。v3.4では動作しv3.5では止まるとのことで、SOCKS5サーバーへ接続したものの受信処理から抜け出せれなくなっているところまでは確認しました。原因を調査します。

**Comment by sayurin** [comment]
b47ad0bce849ef92cad4510278a944a73b2a641c でSOCKS周りの処理を改善した際、構造体にパディングが挿入されていました。これにより通信するデータサイズが誤り、SOCKS5接続できなくなっていました。

**Comment by s-im** [comment]
本日勤務先で確認しましたが、社外のサーバーと通信できるようになっておりました。
素早い対応感謝致します。

**Comment by HiroPANG** [comment]
v5.2～v3.4に変更しても、socksサーバー見つかりませんと表示される

**Comment by sayurin** [comment]
@HiroPANG それだけでは何もわかりません。必要であれば新たなIssueを登録してください。
