### ISSUE TITLE
ファイル一覧の取得で止まる

### ISSUE THREAD

**Issue by riku22** [ffftp/ffftp#94]
ConoHaWINGというレンタルサーバーを利用しています。
Ver.3.7で上記のサーバーに接続すると、ファイル一覧の取得で止まっているようで、一覧が表示されません。
何かこちらで対処可能なことはありますでしょうか。
ちなみに、Ver.2.00を利用したところ、ファイル一覧が取得され、正常に表示されています。
念のため、ログを張り付けておきます。
　なお、ログ中のユーザー名の部分は、勝手ながら一部伏字にさせていただきました。

    FFFTP Ver.3.7 32bit Copyright(C) 1997-2010 Sota & cooperators.
    Copyright (C) 2011-2018 FFFTP Project (Hiromichi Matsushima, Suguru Kawamoto, IWAMOTO Kouichi, vitamin0x, unarist, Asami, fortran90, tomo1192, Yuji Tanaka, Moriguchi Hirokazu, Fu-sen, potato).
    Copyright (C) 2018-2019, KURATA Sayuri.
    INIファイル指定: E:\programs\ffftp\ffftp.ini
    デフォルトのマスターパスワードが使われます.
    マルウェアの攻撃を防ぐため,固有のマスターパスワードを設定することをおすすめします
    ----------------------------
    FTP over Explicit SSL/TLS (FTPES)を使用します.
    ホスト www9.conoha.ne.jp (163.44.187.22:21) に接続しています.
    接続しました.
    220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
    220-You are user number 2 of 50 allowed.
    220-Local time is now 17:56. Server port: 21.
    220-This is a private system - No anonymous login
    220 You will be disconnected after 15 minutes of inactivity.
    >AUTH TLS
    234 AUTH TLS OK.
    >PBSZ 0
    200 PBSZ=0
    >PROT P
    200 Data protection level set to "private"
    >USER riku@xxxxx.com
    331 User riku@xxxxx.com OK. Password required
    >PASS [xxxxxx]
    230 OK. Current restricted directory is /
    >FEAT
    211-Extensions supported:
     EPRT
     IDLE
     MDTM
     SIZE
     MFMT
     REST STREAM
     MLST type*;size*;sizd*;modify*;UNIX.mode*;UNIX.uid*;UNIX.gid*;unique*;
     MLSD
     AUTH TLS
     PBSZ
     PROT
     UTF8
     ESTA
     PASV
     EPSV
     SPSV
     ESTP
    211 End.
    >OPTS UTF8 ON
    200 OK, UTF-8 enabled
    >TYPE A
    200 TYPE is now ASCII
    >PASV
    227 Entering Passive Mode (163,44,187,22,255,20)
    ダウンロードのためにホスト 163.44.187.22 (163.44.187.22:65300) に接続しています.
    接続しました.
    >MLSD
    150 Accepted data connection

**Comment by riku22** [comment]
すみません、いろいろ抜けていたので、追記です。
OSはWindows10 1809を利用しており、Windows Defender以外のウイルス対策ソフトは利用していません。
また、ファイアウォールもWindowsの標準機能のみです。
それから、ほかのサーバーでは、正常に動作しています。
また、Ver.3.0およびVer.3.4以降のバージョンでもテストしてみましたが、同じ現象が発生するようです。

**Comment by sayurin** [comment]
v2.00で動作しv3.0以降では動作しないとのこと了解しました。ただ、いただいている情報だけでは原因を特定できません。
環境はレンタルサーバーのConoHa WINGでしょうか？ 正しければ、15日間の無料お試しがあるようですので、こちらでも試してみます。

**Comment by riku22** [comment]
はい、レンタルサーバーのConoHaWINGです。
それから、こちらでももう少し調べてみたのですが、接続設定の「暗号化」タブにある「FTPS (Explicit)で接続」のチェックを解除して、「暗号化なしで接続を許可」にチェックしたところ、正常につながったので、もしかしたら、SSL関係では？と推測しています。
あくまで勝手な推測ですので、間違っているかもしれませんが。

**Comment by sayurin** [comment]
（無料お試しにクレジットカード登録が要求されてちょっとためらっています。）

暗号化なしではつながるとのこと了解しました。調べたところ、ffftpは[RFC 4217 Securing FTP with TLS](https://tools.ietf.org/html/rfc4217)の記載と少し異なる実装をしているようでした。12.7.  A Firewall-Friendly Data Transfer with Protectionによると

```
              Client                                 Server
     control          data                   data               control
   ====================================================================

     PASV -------------------------------------------------------->
                                             socket()
                                             bind()
         <------------------------------------------ 227 (w,x,y,z,a,b)
                      socket()
     STOR file --------------------------------------------------->
                      connect()  ----------> accept()
         <-------------------------------------------------------- 150
                      TLSneg()   <---------> TLSneg()
                      TLSwrite()  ---------> TLSread()
                      TLSshutdown() -------> TLSshutdown()
                      close()     ---------> close()
         <-------------------------------------------------------- 226
```
ですが、ログファイルでは
```
>PASV
227 Entering Passive Mode (163,44,187,22,255,20)
ダウンロードのためにホスト 163.44.187.22 (163.44.187.22:65300) に接続しています.
接続しました.
>MLSD
150 Accepted data connection
```
となっていて、`STOR file`部分に位置する`MLSD`コマンドよりも先に接続（`connect()`以降の処理）してしまっています。
更に、使用されている[Pure-FTPdはTLS処理をpure-certdに任せている](https://download.pureftpd.org/pub/pure-ftpd/doc/README.TLS)らしく、この順序の違いが原因でPure-FTPdとpure-certdとの連携がうまくできず、データが受信できていない可能性があります。

**Comment by riku22** [comment]
> （無料お試しにクレジットカード登録が要求されてちょっとためらっています。）

　すみません、確かに、そうですね。

　とりあえず、原因はわかったようですが、もし動作テスト等でサーバーが必要ということでしたら、こちらで仮のサーバーを用意することも可能ですが、いかがでしょうか。

**Comment by sayurin** [comment]
こちらで契約し接続してみたのですが、成功してしまいました。証明書も正しく取得できています。ログファイルも比較しましたが、サーバー・ユーザー以外に差異は見られませんでした。`www9.conoha.ne.jp`側の設定ミスの可能性もあり得ますが…うーん、ちょっとわかりません。

```
FFFTP Ver.3.7 32bit Copyright(C) 1997-2010 Sota & cooperators.
Copyright (C) 2011-2018 FFFTP Project (Hiromichi Matsushima, Suguru Kawamoto, IWAMOTO Kouichi, vitamin0x, unarist, Asami, fortran90, tomo1192, Yuji Tanaka, Moriguchi Hirokazu, Fu-sen, potato).
Copyright (C) 2018-2019, KURATA Sayuri.
Default master password is chosen.
Set your own master password in command line to prevent sniff of malwares
----------------------------
Using FTP over Explicit SSL/TLS (FTPES).
Connecting to host www22.conoha.ne.jp (163.44.187.153:21).
Connected.
220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
220-You are user number 1 of 50 allowed.
220-Local time is now 08:57. Server port: 21.
220-This is a private system - No anonymous login
220 You will be disconnected after 15 minutes of inactivity.
>AUTH TLS
234 AUTH TLS OK.
>PBSZ 0
200 PBSZ=0
>PROT P
200 Data protection level set to "private"
>USER test@ffftp.conohawing.com
331 User test@ffftp.conohawing.com OK. Password required
>PASS [xxxxxx]
230 OK. Current restricted directory is /
>FEAT
211-Extensions supported:
 EPRT
 IDLE
 MDTM
 SIZE
 MFMT
 REST STREAM
 MLST type*;size*;sizd*;modify*;UNIX.mode*;UNIX.uid*;UNIX.gid*;unique*;
 MLSD
 AUTH TLS
 PBSZ
 PROT
 UTF8
 ESTA
 PASV
 EPSV
 SPSV
 ESTP
211 End.
>OPTS UTF8 ON
200 OK, UTF-8 enabled
>TYPE A
200 TYPE is now ASCII
>PASV
227 Entering Passive Mode (163,44,187,153,255,49)
Connecting for download to host 163.44.187.153 (163.44.187.153:65329).
Connected.
>MLSD
150 Accepted data connection
226-Options: -a -l
226 11 matches total
Download file list successful. (1218 Bytes)
Determination result of the filename Kanji code is UTF-8.
>XPWD
257 "/" is your current location
>TYPE A
200 TYPE is now ASCII
>PASV
227 Entering Passive Mode (163,44,187,153,255,231)
Connecting for download to host 163.44.187.153 (163.44.187.153:65511).
Connected.
>MLSD
150 Accepted data connection
226-Options: -a -l
226 11 matches total
Download file list successful. (1218 Bytes)
```

![image](https://user-images.githubusercontent.com/3615855/57186096-40e09580-6f14-11e9-8afa-b054cc653142.png)

**Comment by riku22** [comment]
ありがとうございます。
　こちらでももう1つサーバーを作成して試してみました。
　ですが、調査していただいたとおり、こちらでも新しいほうのサーバーには正常に接続できてしまいました。
　www9サーバーのほうに何か問題があるのかもしれません。
　連休明けにでも問い合わせしてみようと思います。
　何か手掛かりが得られればいいのですが。

**Comment by riku22** [comment]
とりあえず、現状報告です。
　ConoHaのサポートの方に問い合わせして、同じアカウントで試してもらっていますが、向こうでは再現しないようです。
　また、あれからこちらでもいろいろ試してみていますが、どうもファイル一覧取得が途中で止まるディレクトリとそうでないディレクトリがあるようで、さっぱり原因がわからなくなってしまいました。
　もうここまでくると環境問題なのでしょうか。
　ただ、手持ちの別のパソコンでも同じような感じなので、そうとも言い切れないかもしれませんが。
　ちなみに、Windows10の設定画面→ネットワークとインターネット→状態→ネットワークのリセットを試したり、Winsockのリセットをしたりしてみましたが、効果なしでした。
　それから、ファイル一覧取得が止まったあとですが、しばらく放置しておくと、タイムアウトになって、再接続して、またファイル一覧の取得を試みているようです。

**Comment by riku22** [comment]
お世話になります。
結局ConoHaのサポートさんからは、サーバーにエラーログ等も残っていないことや向こうの端末では再現しないことなどから、こちらの環境の問題だろうという回答を頂きました。
とりあえず、環境問題ということでこちらのIssueもクローズさせていただきます。
