### ISSUE TITLE
文字コード、濁点、半濁点のフォルダ内に入れません

### ISSUE THREAD

**Issue by ShinbeTorii** [ffftp/ffftp#96]
文字コード、濁点、半濁点のフォルダ内に入れません
エラーコード「550 The system cannot find the file specified.」
Ver3.8 64bit
FTP先には、FTPS（Explict)で接続しています。
ホストの漢字コード：無変換
ファイル名の漢字コード：自動名
他プロジェクトの、FFFTP Ver2では、入れます。

**Comment by sayurin** [comment]
@ShinbeTorii  問題となっているディレクトリ名およびリモート側の実際の文字コードを提示していただけないでしょうか？
またホスト設定で自動変換でなく、明示的に文字コードを指定した場合は動作するのでしょうか？

なお、文字コードを自動判別不可能な文字が多々ありますので、その場合は明示的に指定していただく必要があります。例えば、EUC-JPのほとんどの文字はSHIFT-JISの半角カタカナと解釈できます。

**Comment by ShinbeTorii** [comment]
sayurin様、ご回答ありがとうございます。

ファイル名の漢字コード：SFT-JISと定義することでアクセス可能になりました。
ファイル名の漢字コード：他は全て文字化けやフォルダ内に入れませんでした。

自動でアクセスできない例
マンガ：×
キャプチャ：×
その他：○
ニコニコ：○

この度は、ありがとうございました。

以下に「ファイル名の漢字コード：自動」時のログ記載します。
接続先は、特定の会社公開のFTPのためアドレスは非公開とさせてください。

FFFTP Ver.3.8 64bit Copyright(C) 1997-2010 Sota & cooperators.
Copyright (C) 2011-2018 FFFTP Project (Hiromichi Matsushima, Suguru Kawamoto, IWAMOTO Kouichi, vitamin0x, unarist, Asami, fortran90, tomo1192, Yuji Tanaka, Moriguchi Hirokazu, Fu-sen, potato).
Copyright (C) 2018-2019, KURATA Sayuri.
デフォルトのマスターパスワードが使われます.
マルウェアの攻撃を防ぐため,固有のマスターパスワードを設定することをおすすめします
----------------------------
FTP over Explicit SSL/TLS (FTPES)を使用します.
ホスト ｘｘｘｘｘｘｘ  に接続しています.
接続しました.
220 ｘｘｘｘｘｘｘ  FTP site2
>AUTH TLS
234 AUTH command ok. Expecting TLS Negotiation.
Certificate validation error: 800B010F.
>PBSZ 0
200 PBSZ command successful.
>PROT P
200 PROT command successful.
>USER ｘｘｘｘｘｘｘ
331 Password required
>PASS [ｘｘｘｘｘｘｘ]
230 User logged in.
>FEAT
211-Extended features supported:
 LANG EN*
 UTF8
 AUTH TLS;TLS-C;SSL;TLS-P;
 PBSZ
 PROT C;P;
 CCC
 HOST
 SIZE
 MDTM
 REST STREAM
211 END
>OPTS UTF8 ON
200 OPTS UTF8 command successful - UTF8 encoding now ON.
>TYPE A
200 Type set to A.
>PASV
227 Entering Passive Mode (ｘｘｘｘｘｘｘ).
ダウンロードのためにホスト ｘｘｘｘｘｘｘ (ｘｘｘｘｘｘｘ:10063) に接続しています.
接続しました.
>LIST
125 Data connection already open; Transfer starting.
Certificate validation error: 800B010F.
226 Transfer complete.
ファイル一覧の取得は正常終了しました. (866 Bytes)
ファイル名の漢字コードの判別結果はUTF-8 HFS+です.
>XPWD
257 "/" is current directory.
>TYPE A
200 Type set to A.
>PASV
227 Entering Passive Mode (124,39,162,51,39,77).
ダウンロードのためにホスト 124.39.162.51 (124.39.162.51:10061) に接続しています.
接続しました.
>LIST
125 Data connection already open; Transfer starting.
Certificate validation error: 800B010F.
226 Transfer complete.
ファイル一覧の取得は正常終了しました. (866 Bytes)

**Comment by sayurin** [comment]
詳細確認しました。
マンガ / キャプチャ / その他 / ニコニコ、いずれにおいても正しくShift-JISと判定できていました。

----

> ```
>  ファイル一覧の取得は正常終了しました. (866 Bytes)
> ファイル名の漢字コードの判別結果はUTF-8 HFS+です.
> ```
にヒントが有りました。ffftpの既知の問題として #73 があります。大抵のftpサーバーはルートディレクトリにあまりファイルを置いておらず、あっても日本語文字を含んでいることはほとんどありません。ffftpは、そのほとんど手がかりのないフォルダでのみ文字コードの自動判別を行っているため、全くと言っていいほど機能していません。

その上で、文字化けした状態でのフォルダ移動に成功しない点はどうしようもありません。v3.6までの古い文字コード変換機能でフォルダ移動に成功するのは偶然でしかなく、v3.7以降で失敗するのもたまたまです。
